// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Audio.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundStart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong object_id
        {
            get => __pbn__object_id.GetValueOrDefault();
            set => __pbn__object_id = value;
        }
        public bool ShouldSerializeobject_id() => __pbn__object_id != null;
        public void Resetobject_id() => __pbn__object_id = null;
        private ulong? __pbn__object_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel
        {
            get => __pbn__channel.GetValueOrDefault();
            set => __pbn__channel = value;
        }
        public bool ShouldSerializechannel() => __pbn__channel != null;
        public void Resetchannel() => __pbn__channel = null;
        private uint? __pbn__channel;

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong sound_id { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool is_vox
        {
            get => __pbn__is_vox.GetValueOrDefault();
            set => __pbn__is_vox = value;
        }
        public bool ShouldSerializeis_vox() => __pbn__is_vox != null;
        public void Resetis_vox() => __pbn__is_vox = null;
        private bool? __pbn__is_vox;

        [global::ProtoBuf.ProtoMember(5)]
        public uint joint_name_hash
        {
            get => __pbn__joint_name_hash.GetValueOrDefault();
            set => __pbn__joint_name_hash = value;
        }
        public bool ShouldSerializejoint_name_hash() => __pbn__joint_name_hash != null;
        public void Resetjoint_name_hash() => __pbn__joint_name_hash = null;
        private uint? __pbn__joint_name_hash;

        [global::ProtoBuf.ProtoMember(6)]
        public bool play_on_active_sim_only
        {
            get => __pbn__play_on_active_sim_only.GetValueOrDefault();
            set => __pbn__play_on_active_sim_only = value;
        }
        public bool ShouldSerializeplay_on_active_sim_only() => __pbn__play_on_active_sim_only != null;
        public void Resetplay_on_active_sim_only() => __pbn__play_on_active_sim_only = null;
        private bool? __pbn__play_on_active_sim_only;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string sound_name
        {
            get => __pbn__sound_name ?? "";
            set => __pbn__sound_name = value;
        }
        public bool ShouldSerializesound_name() => __pbn__sound_name != null;
        public void Resetsound_name() => __pbn__sound_name = null;
        private string __pbn__sound_name;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundStop : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong object_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint channel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundSkipToNext : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong object_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint channel { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SoundResource : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ResourceKey sound { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ResourceKey music_track_snippet { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
