// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ChunkPersistence.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkPersistenceEntry : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint dataCRC
        {
            get => __pbn__dataCRC.GetValueOrDefault();
            set => __pbn__dataCRC = value;
        }
        public bool ShouldSerializedataCRC() => __pbn__dataCRC != null;
        public void ResetdataCRC() => __pbn__dataCRC = null;
        private uint? __pbn__dataCRC;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string fileName
        {
            get => __pbn__fileName ?? "";
            set => __pbn__fileName = value;
        }
        public bool ShouldSerializefileName() => __pbn__fileName != null;
        public void ResetfileName() => __pbn__fileName = null;
        private string __pbn__fileName;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChunkPersistenceFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ChunkPersistenceEntry> entries { get; } = new global::System.Collections.Generic.List<ChunkPersistenceEntry>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
