// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ChunkHeaders.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BlueprintThumbnailChunkPackageHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong blueprintID
        {
            get => __pbn__blueprintID.GetValueOrDefault();
            set => __pbn__blueprintID = value;
        }
        public bool ShouldSerializeblueprintID() => __pbn__blueprintID != null;
        public void ResetblueprintID() => __pbn__blueprintID = null;
        private ulong? __pbn__blueprintID;

        [global::ProtoBuf.ProtoMember(2)]
        public uint index
        {
            get => __pbn__index.GetValueOrDefault();
            set => __pbn__index = value;
        }
        public bool ShouldSerializeindex() => __pbn__index != null;
        public void Resetindex() => __pbn__index = null;
        private uint? __pbn__index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotThumbnailChunkPackageHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong blueprintID
        {
            get => __pbn__blueprintID.GetValueOrDefault();
            set => __pbn__blueprintID = value;
        }
        public bool ShouldSerializeblueprintID() => __pbn__blueprintID != null;
        public void ResetblueprintID() => __pbn__blueprintID = null;
        private ulong? __pbn__blueprintID;

        [global::ProtoBuf.ProtoMember(2)]
        public uint index
        {
            get => __pbn__index.GetValueOrDefault();
            set => __pbn__index = value;
        }
        public bool ShouldSerializeindex() => __pbn__index != null;
        public void Resetindex() => __pbn__index = null;
        private uint? __pbn__index;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoriesThumbnailChunkPackageHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong memoryId
        {
            get => __pbn__memoryId.GetValueOrDefault();
            set => __pbn__memoryId = value;
        }
        public bool ShouldSerializememoryId() => __pbn__memoryId != null;
        public void ResetmemoryId() => __pbn__memoryId = null;
        private ulong? __pbn__memoryId;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] simIds { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong householdId
        {
            get => __pbn__householdId.GetValueOrDefault();
            set => __pbn__householdId = value;
        }
        public bool ShouldSerializehouseholdId() => __pbn__householdId != null;
        public void ResethouseholdId() => __pbn__householdId = null;
        private ulong? __pbn__householdId;

        [global::ProtoBuf.ProtoMember(4)]
        public bool favorite
        {
            get => __pbn__favorite.GetValueOrDefault();
            set => __pbn__favorite = value;
        }
        public bool ShouldSerializefavorite() => __pbn__favorite != null;
        public void Resetfavorite() => __pbn__favorite = null;
        private bool? __pbn__favorite;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NeighborhoodThumbnailChunkPackageHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong blueprintID
        {
            get => __pbn__blueprintID.GetValueOrDefault();
            set => __pbn__blueprintID = value;
        }
        public bool ShouldSerializeblueprintID() => __pbn__blueprintID != null;
        public void ResetblueprintID() => __pbn__blueprintID = null;
        private ulong? __pbn__blueprintID;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
