// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: DebugVisualization.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugViz_LineSet : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Line> lines { get; } = new global::System.Collections.Generic.List<Line>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Line : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public Vector3 begin { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public Vector3 end { get; set; }

            [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
            public uint color { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugViz_Text : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Vector2 position_2d { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public Vector3 position_3d { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint color_fg
        {
            get => __pbn__color_fg.GetValueOrDefault();
            set => __pbn__color_fg = value;
        }
        public bool ShouldSerializecolor_fg() => __pbn__color_fg != null;
        public void Resetcolor_fg() => __pbn__color_fg = null;
        private uint? __pbn__color_fg;

        [global::ProtoBuf.ProtoMember(4)]
        public uint color_bg
        {
            get => __pbn__color_bg.GetValueOrDefault();
            set => __pbn__color_bg = value;
        }
        public bool ShouldSerializecolor_bg() => __pbn__color_bg != null;
        public void Resetcolor_bg() => __pbn__color_bg = null;
        private uint? __pbn__color_bg;

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string text { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(Alignment.ALIGN_LEFT)]
        public Alignment alignment
        {
            get => __pbn__alignment ?? Alignment.ALIGN_LEFT;
            set => __pbn__alignment = value;
        }
        public bool ShouldSerializealignment() => __pbn__alignment != null;
        public void Resetalignment() => __pbn__alignment = null;
        private Alignment? __pbn__alignment;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(VertAlign.VERTALIGN_TOP)]
        public VertAlign vertalign
        {
            get => __pbn__vertalign ?? VertAlign.VERTALIGN_TOP;
            set => __pbn__vertalign = value;
        }
        public bool ShouldSerializevertalign() => __pbn__vertalign != null;
        public void Resetvertalign() => __pbn__vertalign = null;
        private VertAlign? __pbn__vertalign;

        [global::ProtoBuf.ProtoMember(8, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong object_id
        {
            get => __pbn__object_id.GetValueOrDefault();
            set => __pbn__object_id = value;
        }
        public bool ShouldSerializeobject_id() => __pbn__object_id != null;
        public void Resetobject_id() => __pbn__object_id = null;
        private ulong? __pbn__object_id;

        [global::ProtoBuf.ProtoMember(9)]
        public int bone_index
        {
            get => __pbn__bone_index.GetValueOrDefault();
            set => __pbn__bone_index = value;
        }
        public bool ShouldSerializebone_index() => __pbn__bone_index != null;
        public void Resetbone_index() => __pbn__bone_index = null;
        private int? __pbn__bone_index;

        [global::ProtoBuf.ProtoContract()]
        public enum Alignment
        {
            ALIGN_LEFT = 0,
            ALIGN_CENTER = 1,
            ALIGN_RIGHT = 2,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum VertAlign
        {
            VERTALIGN_TOP = 0,
            VERTALIGN_MIDDLE = 1,
            VERTALIGN_BOTTOM = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugViz_Layer : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] lines_data
        {
            get => __pbn__lines_data;
            set => __pbn__lines_data = value;
        }
        public bool ShouldSerializelines_data() => __pbn__lines_data != null;
        public void Resetlines_data() => __pbn__lines_data = null;
        private byte[] __pbn__lines_data;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong zoneId
        {
            get => __pbn__zoneId.GetValueOrDefault();
            set => __pbn__zoneId = value;
        }
        public bool ShouldSerializezoneId() => __pbn__zoneId != null;
        public void ResetzoneId() => __pbn__zoneId = null;
        private ulong? __pbn__zoneId;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<DebugViz_Text> text_set { get; } = new global::System.Collections.Generic.List<DebugViz_Text>();

        [global::ProtoBuf.ProtoMember(5)]
        public byte[] tris_data
        {
            get => __pbn__tris_data;
            set => __pbn__tris_data = value;
        }
        public bool ShouldSerializetris_data() => __pbn__tris_data != null;
        public void Resettris_data() => __pbn__tris_data = null;
        private byte[] __pbn__tris_data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DebugViz_LayerUpdateNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string layerName { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong zoneId
        {
            get => __pbn__zoneId.GetValueOrDefault();
            set => __pbn__zoneId = value;
        }
        public bool ShouldSerializezoneId() => __pbn__zoneId != null;
        public void ResetzoneId() => __pbn__zoneId = null;
        private ulong? __pbn__zoneId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
