// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Events.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class EventDefinition : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string event_id
        {
            get => __pbn__event_id ?? "";
            set => __pbn__event_id = value;
        }
        public bool ShouldSerializeevent_id() => __pbn__event_id != null;
        public void Resetevent_id() => __pbn__event_id = null;
        private string __pbn__event_id;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedDateAndTimeData start_date { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedDateAndTimeData end_date { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string event_type
        {
            get => __pbn__event_type ?? "";
            set => __pbn__event_type = value;
        }
        public bool ShouldSerializeevent_type() => __pbn__event_type != null;
        public void Resetevent_type() => __pbn__event_type = null;
        private string __pbn__event_type;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description
        {
            get => __pbn__description ?? "";
            set => __pbn__description = value;
        }
        public bool ShouldSerializedescription() => __pbn__description != null;
        public void Resetdescription() => __pbn__description = null;
        private string __pbn__description;

        [global::ProtoBuf.ProtoMember(7)]
        public global::System.Collections.Generic.List<RewardPeriod> reward_periods { get; } = new global::System.Collections.Generic.List<RewardPeriod>();

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<EventProgressReward> progress_rewards { get; } = new global::System.Collections.Generic.List<EventProgressReward>();

        [global::ProtoBuf.ProtoMember(9)]
        public LocalizedDateAndTimeData grace_period_end_date { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public LocalizedDateAndTimeData last_revision_time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardPeriod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint reward_period_id
        {
            get => __pbn__reward_period_id.GetValueOrDefault();
            set => __pbn__reward_period_id = value;
        }
        public bool ShouldSerializereward_period_id() => __pbn__reward_period_id != null;
        public void Resetreward_period_id() => __pbn__reward_period_id = null;
        private uint? __pbn__reward_period_id;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedDateAndTimeData start_date { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedDateAndTimeData end_date { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<Quest> quests { get; } = new global::System.Collections.Generic.List<Quest>();

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<CatchUpPeriod> catch_up_periods { get; } = new global::System.Collections.Generic.List<CatchUpPeriod>();

        [global::ProtoBuf.ProtoMember(7)]
        public long max_xp
        {
            get => __pbn__max_xp.GetValueOrDefault();
            set => __pbn__max_xp = value;
        }
        public bool ShouldSerializemax_xp() => __pbn__max_xp != null;
        public void Resetmax_xp() => __pbn__max_xp = null;
        private long? __pbn__max_xp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Reward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public long reward_id
        {
            get => __pbn__reward_id.GetValueOrDefault();
            set => __pbn__reward_id = value;
        }
        public bool ShouldSerializereward_id() => __pbn__reward_id != null;
        public void Resetreward_id() => __pbn__reward_id = null;
        private long? __pbn__reward_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(RewardType.REWARD_TYPE_UNKNOWN)]
        public RewardType reward_type
        {
            get => __pbn__reward_type ?? RewardType.REWARD_TYPE_UNKNOWN;
            set => __pbn__reward_type = value;
        }
        public bool ShouldSerializereward_type() => __pbn__reward_type != null;
        public void Resetreward_type() => __pbn__reward_type = null;
        private RewardType? __pbn__reward_type;

        [global::ProtoBuf.ProtoMember(3)]
        public long amount
        {
            get => __pbn__amount.GetValueOrDefault();
            set => __pbn__amount = value;
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventProgressReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint progress_id
        {
            get => __pbn__progress_id.GetValueOrDefault();
            set => __pbn__progress_id = value;
        }
        public bool ShouldSerializeprogress_id() => __pbn__progress_id != null;
        public void Resetprogress_id() => __pbn__progress_id = null;
        private uint? __pbn__progress_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(ProgressType.PROGRESS_TYPE_UNKNOWN)]
        public ProgressType type
        {
            get => __pbn__type ?? ProgressType.PROGRESS_TYPE_UNKNOWN;
            set => __pbn__type = value;
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private ProgressType? __pbn__type;

        [global::ProtoBuf.ProtoMember(3)]
        public long target_xp
        {
            get => __pbn__target_xp.GetValueOrDefault();
            set => __pbn__target_xp = value;
        }
        public bool ShouldSerializetarget_xp() => __pbn__target_xp != null;
        public void Resettarget_xp() => __pbn__target_xp = null;
        private long? __pbn__target_xp;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<Reward> rewards { get; } = new global::System.Collections.Generic.List<Reward>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProgressReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint progress_id
        {
            get => __pbn__progress_id.GetValueOrDefault();
            set => __pbn__progress_id = value;
        }
        public bool ShouldSerializeprogress_id() => __pbn__progress_id != null;
        public void Resetprogress_id() => __pbn__progress_id = null;
        private uint? __pbn__progress_id;

        [global::ProtoBuf.ProtoMember(2)]
        public bool reward_unlocked
        {
            get => __pbn__reward_unlocked.GetValueOrDefault();
            set => __pbn__reward_unlocked = value;
        }
        public bool ShouldSerializereward_unlocked() => __pbn__reward_unlocked != null;
        public void Resetreward_unlocked() => __pbn__reward_unlocked = null;
        private bool? __pbn__reward_unlocked;

        [global::ProtoBuf.ProtoMember(3)]
        public bool reward_claimed
        {
            get => __pbn__reward_claimed.GetValueOrDefault();
            set => __pbn__reward_claimed = value;
        }
        public bool ShouldSerializereward_claimed() => __pbn__reward_claimed != null;
        public void Resetreward_claimed() => __pbn__reward_claimed = null;
        private bool? __pbn__reward_claimed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventProgressResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<EventProgress> event_progress { get; } = new global::System.Collections.Generic.List<EventProgress>();

        [global::ProtoBuf.ProtoContract()]
        public partial class EventProgress : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string event_id
            {
                get => __pbn__event_id ?? "";
                set => __pbn__event_id = value;
            }
            public bool ShouldSerializeevent_id() => __pbn__event_id != null;
            public void Resetevent_id() => __pbn__event_id = null;
            private string __pbn__event_id;

            [global::ProtoBuf.ProtoMember(2)]
            public long event_xp
            {
                get => __pbn__event_xp.GetValueOrDefault();
                set => __pbn__event_xp = value;
            }
            public bool ShouldSerializeevent_xp() => __pbn__event_xp != null;
            public void Resetevent_xp() => __pbn__event_xp = null;
            private long? __pbn__event_xp;

            [global::ProtoBuf.ProtoMember(3)]
            public global::System.Collections.Generic.List<RewardPeriodProgress> progress { get; } = new global::System.Collections.Generic.List<RewardPeriodProgress>();

            [global::ProtoBuf.ProtoMember(4)]
            public global::System.Collections.Generic.List<ProgressReward> progress_rewards { get; } = new global::System.Collections.Generic.List<ProgressReward>();

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Quest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint quest_id
        {
            get => __pbn__quest_id.GetValueOrDefault();
            set => __pbn__quest_id = value;
        }
        public bool ShouldSerializequest_id() => __pbn__quest_id != null;
        public void Resetquest_id() => __pbn__quest_id = null;
        private uint? __pbn__quest_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tuning_instance_id
        {
            get => __pbn__tuning_instance_id.GetValueOrDefault();
            set => __pbn__tuning_instance_id = value;
        }
        public bool ShouldSerializetuning_instance_id() => __pbn__tuning_instance_id != null;
        public void Resettuning_instance_id() => __pbn__tuning_instance_id = null;
        private uint? __pbn__tuning_instance_id;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string quest_name
        {
            get => __pbn__quest_name ?? "";
            set => __pbn__quest_name = value;
        }
        public bool ShouldSerializequest_name() => __pbn__quest_name != null;
        public void Resetquest_name() => __pbn__quest_name = null;
        private string __pbn__quest_name;

        [global::ProtoBuf.ProtoMember(4)]
        public long xp
        {
            get => __pbn__xp.GetValueOrDefault();
            set => __pbn__xp = value;
        }
        public bool ShouldSerializexp() => __pbn__xp != null;
        public void Resetxp() => __pbn__xp = null;
        private long? __pbn__xp;

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<QuestObjective> objectives { get; } = new global::System.Collections.Generic.List<QuestObjective>();

        [global::ProtoBuf.ProtoMember(6)]
        public bool is_canceled
        {
            get => __pbn__is_canceled.GetValueOrDefault();
            set => __pbn__is_canceled = value;
        }
        public bool ShouldSerializeis_canceled() => __pbn__is_canceled != null;
        public void Resetis_canceled() => __pbn__is_canceled = null;
        private bool? __pbn__is_canceled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestObjective : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint objective_id
        {
            get => __pbn__objective_id.GetValueOrDefault();
            set => __pbn__objective_id = value;
        }
        public bool ShouldSerializeobjective_id() => __pbn__objective_id != null;
        public void Resetobjective_id() => __pbn__objective_id = null;
        private uint? __pbn__objective_id;

        [global::ProtoBuf.ProtoMember(2)]
        public long xp
        {
            get => __pbn__xp.GetValueOrDefault();
            set => __pbn__xp = value;
        }
        public bool ShouldSerializexp() => __pbn__xp != null;
        public void Resetxp() => __pbn__xp = null;
        private long? __pbn__xp;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(4)]
        public bool is_canceled
        {
            get => __pbn__is_canceled.GetValueOrDefault();
            set => __pbn__is_canceled = value;
        }
        public bool ShouldSerializeis_canceled() => __pbn__is_canceled != null;
        public void Resetis_canceled() => __pbn__is_canceled = null;
        private bool? __pbn__is_canceled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CatchUpPeriod : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint catch_up_id
        {
            get => __pbn__catch_up_id.GetValueOrDefault();
            set => __pbn__catch_up_id = value;
        }
        public bool ShouldSerializecatch_up_id() => __pbn__catch_up_id != null;
        public void Resetcatch_up_id() => __pbn__catch_up_id = null;
        private uint? __pbn__catch_up_id;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedDateAndTimeData start_date { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedDateAndTimeData end_date { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public float xp_multiplier
        {
            get => __pbn__xp_multiplier.GetValueOrDefault();
            set => __pbn__xp_multiplier = value;
        }
        public bool ShouldSerializexp_multiplier() => __pbn__xp_multiplier != null;
        public void Resetxp_multiplier() => __pbn__xp_multiplier = null;
        private float? __pbn__xp_multiplier;

        [global::ProtoBuf.ProtoMember(5)]
        public bool is_enabled
        {
            get => __pbn__is_enabled.GetValueOrDefault();
            set => __pbn__is_enabled = value;
        }
        public bool ShouldSerializeis_enabled() => __pbn__is_enabled != null;
        public void Resetis_enabled() => __pbn__is_enabled = null;
        private bool? __pbn__is_enabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ClaimedRewardUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string event_id
        {
            get => __pbn__event_id ?? "";
            set => __pbn__event_id = value;
        }
        public bool ShouldSerializeevent_id() => __pbn__event_id != null;
        public void Resetevent_id() => __pbn__event_id = null;
        private string __pbn__event_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] claimed_progress_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(EventOpResponse.EVOP_UNKNOWN)]
        public EventOpResponse response_code
        {
            get => __pbn__response_code ?? EventOpResponse.EVOP_UNKNOWN;
            set => __pbn__response_code = value;
        }
        public bool ShouldSerializeresponse_code() => __pbn__response_code != null;
        public void Resetresponse_code() => __pbn__response_code = null;
        private EventOpResponse? __pbn__response_code;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string description
        {
            get => __pbn__description ?? "";
            set => __pbn__description = value;
        }
        public bool ShouldSerializedescription() => __pbn__description != null;
        public void Resetdescription() => __pbn__description = null;
        private string __pbn__description;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestObjectiveProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint objective_id
        {
            get => __pbn__objective_id.GetValueOrDefault();
            set => __pbn__objective_id = value;
        }
        public bool ShouldSerializeobjective_id() => __pbn__objective_id != null;
        public void Resetobjective_id() => __pbn__objective_id = null;
        private uint? __pbn__objective_id;

        [global::ProtoBuf.ProtoMember(2)]
        public long xp
        {
            get => __pbn__xp.GetValueOrDefault();
            set => __pbn__xp = value;
        }
        public bool ShouldSerializexp() => __pbn__xp != null;
        public void Resetxp() => __pbn__xp = null;
        private long? __pbn__xp;

        [global::ProtoBuf.ProtoMember(3)]
        public uint catch_up_id
        {
            get => __pbn__catch_up_id.GetValueOrDefault();
            set => __pbn__catch_up_id = value;
        }
        public bool ShouldSerializecatch_up_id() => __pbn__catch_up_id != null;
        public void Resetcatch_up_id() => __pbn__catch_up_id = null;
        private uint? __pbn__catch_up_id;

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedDateAndTimeData completion_time { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool completed
        {
            get => __pbn__completed.GetValueOrDefault();
            set => __pbn__completed = value;
        }
        public bool ShouldSerializecompleted() => __pbn__completed != null;
        public void Resetcompleted() => __pbn__completed = null;
        private bool? __pbn__completed;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QuestProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint quest_id
        {
            get => __pbn__quest_id.GetValueOrDefault();
            set => __pbn__quest_id = value;
        }
        public bool ShouldSerializequest_id() => __pbn__quest_id != null;
        public void Resetquest_id() => __pbn__quest_id = null;
        private uint? __pbn__quest_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<QuestObjectiveProgress> quest_objective_progress { get; } = new global::System.Collections.Generic.List<QuestObjectiveProgress>();

        [global::ProtoBuf.ProtoMember(3)]
        public long xp
        {
            get => __pbn__xp.GetValueOrDefault();
            set => __pbn__xp = value;
        }
        public bool ShouldSerializexp() => __pbn__xp != null;
        public void Resetxp() => __pbn__xp = null;
        private long? __pbn__xp;

        [global::ProtoBuf.ProtoMember(4)]
        public uint catch_up_id
        {
            get => __pbn__catch_up_id.GetValueOrDefault();
            set => __pbn__catch_up_id = value;
        }
        public bool ShouldSerializecatch_up_id() => __pbn__catch_up_id != null;
        public void Resetcatch_up_id() => __pbn__catch_up_id = null;
        private uint? __pbn__catch_up_id;

        [global::ProtoBuf.ProtoMember(5)]
        public LocalizedDateAndTimeData completion_time { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool completed
        {
            get => __pbn__completed.GetValueOrDefault();
            set => __pbn__completed = value;
        }
        public bool ShouldSerializecompleted() => __pbn__completed != null;
        public void Resetcompleted() => __pbn__completed = null;
        private bool? __pbn__completed;

        [global::ProtoBuf.ProtoMember(7)]
        public bool canceled
        {
            get => __pbn__canceled.GetValueOrDefault();
            set => __pbn__canceled = value;
        }
        public bool ShouldSerializecanceled() => __pbn__canceled != null;
        public void Resetcanceled() => __pbn__canceled = null;
        private bool? __pbn__canceled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventProgressUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string event_id
        {
            get => __pbn__event_id ?? "";
            set => __pbn__event_id = value;
        }
        public bool ShouldSerializeevent_id() => __pbn__event_id != null;
        public void Resetevent_id() => __pbn__event_id = null;
        private string __pbn__event_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<RewardPeriodProgress> progress { get; } = new global::System.Collections.Generic.List<RewardPeriodProgress>();

        [global::ProtoBuf.ProtoMember(3)]
        public long event_xp
        {
            get => __pbn__event_xp.GetValueOrDefault();
            set => __pbn__event_xp = value;
        }
        public bool ShouldSerializeevent_xp() => __pbn__event_xp != null;
        public void Resetevent_xp() => __pbn__event_xp = null;
        private long? __pbn__event_xp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RewardPeriodProgress : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint reward_period_id
        {
            get => __pbn__reward_period_id.GetValueOrDefault();
            set => __pbn__reward_period_id = value;
        }
        public bool ShouldSerializereward_period_id() => __pbn__reward_period_id != null;
        public void Resetreward_period_id() => __pbn__reward_period_id = null;
        private uint? __pbn__reward_period_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<QuestProgress> quest_progress { get; } = new global::System.Collections.Generic.List<QuestProgress>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerInventoryResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Reward> rewards { get; } = new global::System.Collections.Generic.List<Reward>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class EventsControlMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public EventsOpTypes opCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong transactionId
        {
            get => __pbn__transactionId.GetValueOrDefault();
            set => __pbn__transactionId = value;
        }
        public bool ShouldSerializetransactionId() => __pbn__transactionId != null;
        public void ResettransactionId() => __pbn__transactionId = null;
        private ulong? __pbn__transactionId;

        [global::ProtoBuf.ProtoMember(3)]
        public ServerResponse response { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<EventDefinition> event_definition { get; } = new global::System.Collections.Generic.List<EventDefinition>();

        [global::ProtoBuf.ProtoMember(5)]
        public EventProgressUpdate event_progress_update { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ClaimedRewardUpdate claimed_reward_update { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public EventProgressResponse event_progress_response { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public PlayerInventoryResponse player_inventory_response { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(EventVersion.UNKNOWN)]
        public EventVersion max_event_version
        {
            get => __pbn__max_event_version ?? EventVersion.UNKNOWN;
            set => __pbn__max_event_version = value;
        }
        public bool ShouldSerializemax_event_version() => __pbn__max_event_version != null;
        public void Resetmax_event_version() => __pbn__max_event_version = null;
        private EventVersion? __pbn__max_event_version;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EventVersion
    {
        UNKNOWN = 0,
        R3_EVENT = 100,
        DEC_EVENT = 200,
        R4_EVENT = 300,
        R5_EVENT = 400,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
