// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Lot.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LotInfoItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get => __pbn__name ?? "";
            set => __pbn__name = value;
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        public uint world_id
        {
            get => __pbn__world_id.GetValueOrDefault();
            set => __pbn__world_id = value;
        }
        public bool ShouldSerializeworld_id() => __pbn__world_id != null;
        public void Resetworld_id() => __pbn__world_id = null;
        private uint? __pbn__world_id;

        [global::ProtoBuf.ProtoMember(4)]
        public uint lot_template_id
        {
            get => __pbn__lot_template_id.GetValueOrDefault();
            set => __pbn__lot_template_id = value;
        }
        public bool ShouldSerializelot_template_id() => __pbn__lot_template_id != null;
        public void Resetlot_template_id() => __pbn__lot_template_id = null;
        private uint? __pbn__lot_template_id;

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong lot_description_id
        {
            get => __pbn__lot_description_id.GetValueOrDefault();
            set => __pbn__lot_description_id = value;
        }
        public bool ShouldSerializelot_description_id() => __pbn__lot_description_id != null;
        public void Resetlot_description_id() => __pbn__lot_description_id = null;
        private ulong? __pbn__lot_description_id;

        [global::ProtoBuf.ProtoMember(6)]
        public LocalizedString venue_type_name { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string household_name
        {
            get => __pbn__household_name ?? "";
            set => __pbn__household_name = value;
        }
        public bool ShouldSerializehousehold_name() => __pbn__household_name != null;
        public void Resethousehold_name() => __pbn__household_name = null;
        private string __pbn__household_name;

        [global::ProtoBuf.ProtoMember(8)]
        public ResourceKey venue_type { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint region_description_id
        {
            get => __pbn__region_description_id.GetValueOrDefault();
            set => __pbn__region_description_id = value;
        }
        public bool ShouldSerializeregion_description_id() => __pbn__region_description_id != null;
        public void Resetregion_description_id() => __pbn__region_description_id = null;
        private uint? __pbn__region_description_id;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string region_name
        {
            get => __pbn__region_name ?? "";
            set => __pbn__region_name = value;
        }
        public bool ShouldSerializeregion_name() => __pbn__region_name != null;
        public void Resetregion_name() => __pbn__region_name = null;
        private string __pbn__region_name;

        [global::ProtoBuf.ProtoMember(11)]
        public ResourceKey region_icon { get; set; }

        [global::ProtoBuf.ProtoMember(12, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong house_description_id
        {
            get => __pbn__house_description_id.GetValueOrDefault();
            set => __pbn__house_description_id = value;
        }
        public bool ShouldSerializehouse_description_id() => __pbn__house_description_id != null;
        public void Resethouse_description_id() => __pbn__house_description_id = null;
        private ulong? __pbn__house_description_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotPlexExteriorUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint plex_exterior_house_desc_id
        {
            get => __pbn__plex_exterior_house_desc_id.GetValueOrDefault();
            set => __pbn__plex_exterior_house_desc_id = value;
        }
        public bool ShouldSerializeplex_exterior_house_desc_id() => __pbn__plex_exterior_house_desc_id != null;
        public void Resetplex_exterior_house_desc_id() => __pbn__plex_exterior_house_desc_id = null;
        private uint? __pbn__plex_exterior_house_desc_id;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
