// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: LotTemplate.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LotObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong id
        {
            get => __pbn__id.GetValueOrDefault();
            set => __pbn__id = value;
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private ulong? __pbn__id;

        [global::ProtoBuf.ProtoMember(3)]
        public Transform quat_pos { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint object_def_guid
        {
            get => __pbn__object_def_guid.GetValueOrDefault();
            set => __pbn__object_def_guid = value;
        }
        public bool ShouldSerializeobject_def_guid() => __pbn__object_def_guid != null;
        public void Resetobject_def_guid() => __pbn__object_def_guid = null;
        private uint? __pbn__object_def_guid;

        [global::ProtoBuf.ProtoMember(5)]
        public int level
        {
            get => __pbn__level.GetValueOrDefault();
            set => __pbn__level = value;
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong parent_id
        {
            get => __pbn__parent_id.GetValueOrDefault();
            set => __pbn__parent_id = value;
        }
        public bool ShouldSerializeparent_id() => __pbn__parent_id != null;
        public void Resetparent_id() => __pbn__parent_id = null;
        private ulong? __pbn__parent_id;

        [global::ProtoBuf.ProtoMember(7)]
        public uint slot_hash
        {
            get => __pbn__slot_hash.GetValueOrDefault();
            set => __pbn__slot_hash = value;
        }
        public bool ShouldSerializeslot_hash() => __pbn__slot_hash != null;
        public void Resetslot_hash() => __pbn__slot_hash = null;
        private uint? __pbn__slot_hash;

        [global::ProtoBuf.ProtoMember(8)]
        public uint slot_index
        {
            get => __pbn__slot_index.GetValueOrDefault();
            set => __pbn__slot_index = value;
        }
        public bool ShouldSerializeslot_index() => __pbn__slot_index != null;
        public void Resetslot_index() => __pbn__slot_index = null;
        private uint? __pbn__slot_index;

        [global::ProtoBuf.ProtoMember(9)]
        public uint object_state_idx
        {
            get => __pbn__object_state_idx.GetValueOrDefault();
            set => __pbn__object_state_idx = value;
        }
        public bool ShouldSerializeobject_state_idx() => __pbn__object_state_idx != null;
        public void Resetobject_state_idx() => __pbn__object_state_idx = null;
        private uint? __pbn__object_state_idx;

        [global::ProtoBuf.ProtoMember(10)]
        public uint parent_type
        {
            get => __pbn__parent_type.GetValueOrDefault();
            set => __pbn__parent_type = value;
        }
        public bool ShouldSerializeparent_type() => __pbn__parent_type != null;
        public void Resetparent_type() => __pbn__parent_type = null;
        private uint? __pbn__parent_type;

        [global::ProtoBuf.ProtoMember(11)]
        public ulong parent_location
        {
            get => __pbn__parent_location.GetValueOrDefault();
            set => __pbn__parent_location = value;
        }
        public bool ShouldSerializeparent_location() => __pbn__parent_location != null;
        public void Resetparent_location() => __pbn__parent_location = null;
        private ulong? __pbn__parent_location;

        [global::ProtoBuf.ProtoMember(12)]
        public Vector3 light_color { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public float scale
        {
            get => __pbn__scale.GetValueOrDefault();
            set => __pbn__scale = value;
        }
        public bool ShouldSerializescale() => __pbn__scale != null;
        public void Resetscale() => __pbn__scale = null;
        private float? __pbn__scale;

        [global::ProtoBuf.ProtoMember(14)]
        public float light_dimmer_value
        {
            get => __pbn__light_dimmer_value.GetValueOrDefault();
            set => __pbn__light_dimmer_value = value;
        }
        public bool ShouldSerializelight_dimmer_value() => __pbn__light_dimmer_value != null;
        public void Resetlight_dimmer_value() => __pbn__light_dimmer_value = null;
        private float? __pbn__light_dimmer_value;

        [global::ProtoBuf.ProtoMember(15)]
        public ulong object_def_guid64
        {
            get => __pbn__object_def_guid64.GetValueOrDefault();
            set => __pbn__object_def_guid64 = value;
        }
        public bool ShouldSerializeobject_def_guid64() => __pbn__object_def_guid64 != null;
        public void Resetobject_def_guid64() => __pbn__object_def_guid64 = null;
        private ulong? __pbn__object_def_guid64;

        [global::ProtoBuf.ProtoMember(16)]
        public uint geo_state_id
        {
            get => __pbn__geo_state_id.GetValueOrDefault();
            set => __pbn__geo_state_id = value;
        }
        public bool ShouldSerializegeo_state_id() => __pbn__geo_state_id != null;
        public void Resetgeo_state_id() => __pbn__geo_state_id = null;
        private uint? __pbn__geo_state_id;

        [global::ProtoBuf.ProtoMember(17)]
        public ResourceKey model_override_key { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public uint material_state_id
        {
            get => __pbn__material_state_id.GetValueOrDefault();
            set => __pbn__material_state_id = value;
        }
        public bool ShouldSerializematerial_state_id() => __pbn__material_state_id != null;
        public void Resetmaterial_state_id() => __pbn__material_state_id = null;
        private uint? __pbn__material_state_id;

        [global::ProtoBuf.ProtoMember(19)]
        public uint buildbuy_use_flags
        {
            get => __pbn__buildbuy_use_flags.GetValueOrDefault();
            set => __pbn__buildbuy_use_flags = value;
        }
        public bool ShouldSerializebuildbuy_use_flags() => __pbn__buildbuy_use_flags != null;
        public void Resetbuildbuy_use_flags() => __pbn__buildbuy_use_flags = null;
        private uint? __pbn__buildbuy_use_flags;

        [global::ProtoBuf.ProtoMember(20, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong texture_id
        {
            get => __pbn__texture_id.GetValueOrDefault();
            set => __pbn__texture_id = value;
        }
        public bool ShouldSerializetexture_id() => __pbn__texture_id != null;
        public void Resettexture_id() => __pbn__texture_id = null;
        private ulong? __pbn__texture_id;

        [global::ProtoBuf.ProtoMember(21)]
        public byte[] attributes
        {
            get => __pbn__attributes;
            set => __pbn__attributes = value;
        }
        public bool ShouldSerializeattributes() => __pbn__attributes != null;
        public void Resetattributes() => __pbn__attributes = null;
        private byte[] __pbn__attributes;

        [global::ProtoBuf.ProtoMember(22)]
        public uint material_variant
        {
            get => __pbn__material_variant.GetValueOrDefault();
            set => __pbn__material_variant = value;
        }
        public bool ShouldSerializematerial_variant() => __pbn__material_variant != null;
        public void Resetmaterial_variant() => __pbn__material_variant = null;
        private uint? __pbn__material_variant;

        [global::ProtoBuf.ProtoMember(23)]
        public uint texture_effect
        {
            get => __pbn__texture_effect.GetValueOrDefault();
            set => __pbn__texture_effect = value;
        }
        public bool ShouldSerializetexture_effect() => __pbn__texture_effect != null;
        public void Resettexture_effect() => __pbn__texture_effect = null;
        private uint? __pbn__texture_effect;

        [global::ProtoBuf.ProtoMember(24)]
        public global::System.Collections.Generic.List<Vector3> multicolor { get; } = new global::System.Collections.Generic.List<Vector3>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotObjectList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint lot_id
        {
            get => __pbn__lot_id.GetValueOrDefault();
            set => __pbn__lot_id = value;
        }
        public bool ShouldSerializelot_id() => __pbn__lot_id != null;
        public void Resetlot_id() => __pbn__lot_id = null;
        private uint? __pbn__lot_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<LotObject> lot_objects { get; } = new global::System.Collections.Generic.List<LotObject>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotTemplate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LotObjectList lot_object_list { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] architecture
        {
            get => __pbn__architecture;
            set => __pbn__architecture = value;
        }
        public bool ShouldSerializearchitecture() => __pbn__architecture != null;
        public void Resetarchitecture() => __pbn__architecture = null;
        private byte[] __pbn__architecture;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
