// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Memories.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoriesList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong simId
        {
            get => __pbn__simId.GetValueOrDefault();
            set => __pbn__simId = value;
        }
        public bool ShouldSerializesimId() => __pbn__simId != null;
        public void ResetsimId() => __pbn__simId = null;
        private ulong? __pbn__simId;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong householdId
        {
            get => __pbn__householdId.GetValueOrDefault();
            set => __pbn__householdId = value;
        }
        public bool ShouldSerializehouseholdId() => __pbn__householdId != null;
        public void ResethouseholdId() => __pbn__householdId = null;
        private ulong? __pbn__householdId;

        [global::ProtoBuf.ProtoMember(3)]
        public bool isFavorites
        {
            get => __pbn__isFavorites.GetValueOrDefault();
            set => __pbn__isFavorites = value;
        }
        public bool ShouldSerializeisFavorites() => __pbn__isFavorites != null;
        public void ResetisFavorites() => __pbn__isFavorites = null;
        private bool? __pbn__isFavorites;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong[] memoryIds { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MemoriesFilterFile : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<MemoriesList> lists { get; } = new global::System.Collections.Generic.List<MemoriesList>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
