// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: PersistenceBlobs.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Persistence
{

    [global::ProtoBuf.ProtoContract()]
    public partial class BlobSimFacialCustomizationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong[] sculpts { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<Modifier> face_modifiers { get; } = new global::System.Collections.Generic.List<Modifier>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<Modifier> body_modifiers { get; } = new global::System.Collections.Generic.List<Modifier>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<Modifier> aged_face_modifiers { get; } = new global::System.Collections.Generic.List<Modifier>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<Modifier> aged_body_modifiers { get; } = new global::System.Collections.Generic.List<Modifier>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Modifier : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1)]
            public ulong key
            {
                get => __pbn__key.GetValueOrDefault();
                set => __pbn__key = value;
            }
            public bool ShouldSerializekey() => __pbn__key != null;
            public void Resetkey() => __pbn__key = null;
            private ulong? __pbn__key;

            [global::ProtoBuf.ProtoMember(2)]
            public float amount
            {
                get => __pbn__amount.GetValueOrDefault();
                set => __pbn__amount = value;
            }
            public bool ShouldSerializeamount() => __pbn__amount != null;
            public void Resetamount() => __pbn__amount = null;
            private float? __pbn__amount;

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
