// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ResourceKey.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceKey : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint type
        {
            get => __pbn__type.GetValueOrDefault();
            set => __pbn__type = value;
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private uint? __pbn__type;

        [global::ProtoBuf.ProtoMember(2)]
        public uint group
        {
            get => __pbn__group.GetValueOrDefault();
            set => __pbn__group = value;
        }
        public bool ShouldSerializegroup() => __pbn__group != null;
        public void Resetgroup() => __pbn__group = null;
        private uint? __pbn__group;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong instance
        {
            get => __pbn__instance.GetValueOrDefault();
            set => __pbn__instance = value;
        }
        public bool ShouldSerializeinstance() => __pbn__instance != null;
        public void Resetinstance() => __pbn__instance = null;
        private ulong? __pbn__instance;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceKeyList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ResourceKey> resource_keys { get; } = new global::System.Collections.Generic.List<ResourceKey>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
