// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SituationPersistence.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Persistence
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong goal_type_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong actor_id
        {
            get => __pbn__actor_id.GetValueOrDefault();
            set => __pbn__actor_id = value;
        }
        public bool ShouldSerializeactor_id() => __pbn__actor_id != null;
        public void Resetactor_id() => __pbn__actor_id = null;
        private ulong? __pbn__actor_id;

        [global::ProtoBuf.ProtoMember(3)]
        public uint count
        {
            get => __pbn__count.GetValueOrDefault();
            set => __pbn__count = value;
        }
        public bool ShouldSerializecount() => __pbn__count != null;
        public void Resetcount() => __pbn__count = null;
        private uint? __pbn__count;

        [global::ProtoBuf.ProtoMember(4)]
        public bool completed
        {
            get => __pbn__completed.GetValueOrDefault();
            set => __pbn__completed = value;
        }
        public bool ShouldSerializecompleted() => __pbn__completed != null;
        public void Resetcompleted() => __pbn__completed = null;
        private bool? __pbn__completed;

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong chain_id
        {
            get => __pbn__chain_id.GetValueOrDefault();
            set => __pbn__chain_id = value;
        }
        public bool ShouldSerializechain_id() => __pbn__chain_id != null;
        public void Resetchain_id() => __pbn__chain_id = null;
        private ulong? __pbn__chain_id;

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] custom_data
        {
            get => __pbn__custom_data;
            set => __pbn__custom_data = value;
        }
        public bool ShouldSerializecustom_data() => __pbn__custom_data != null;
        public void Resetcustom_data() => __pbn__custom_data = null;
        private byte[] __pbn__custom_data;

        [global::ProtoBuf.ProtoMember(7)]
        public bool locked
        {
            get => __pbn__locked.GetValueOrDefault();
            set => __pbn__locked = value;
        }
        public bool ShouldSerializelocked() => __pbn__locked != null;
        public void Resetlocked() => __pbn__locked = null;
        private bool? __pbn__locked;

        [global::ProtoBuf.ProtoMember(8)]
        public ulong completed_time
        {
            get => __pbn__completed_time.GetValueOrDefault();
            set => __pbn__completed_time = value;
        }
        public bool ShouldSerializecompleted_time() => __pbn__completed_time != null;
        public void Resetcompleted_time() => __pbn__completed_time = null;
        private ulong? __pbn__completed_time;

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong target_id
        {
            get => __pbn__target_id.GetValueOrDefault();
            set => __pbn__target_id = value;
        }
        public bool ShouldSerializetarget_id() => __pbn__target_id != null;
        public void Resettarget_id() => __pbn__target_id = null;
        private ulong? __pbn__target_id;

        [global::ProtoBuf.ProtoMember(10, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong secondary_target_id
        {
            get => __pbn__secondary_target_id.GetValueOrDefault();
            set => __pbn__secondary_target_id = value;
        }
        public bool ShouldSerializesecondary_target_id() => __pbn__secondary_target_id != null;
        public void Resetsecondary_target_id() => __pbn__secondary_target_id = null;
        private ulong? __pbn__secondary_target_id;

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<SituationGoalData> sub_goals { get; } = new global::System.Collections.Generic.List<SituationGoalData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CompletedSituationGoalData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public SituationGoalData situation_goal { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong chosen_goal_set_type_id
        {
            get => __pbn__chosen_goal_set_type_id.GetValueOrDefault();
            set => __pbn__chosen_goal_set_type_id = value;
        }
        public bool ShouldSerializechosen_goal_set_type_id() => __pbn__chosen_goal_set_type_id != null;
        public void Resetchosen_goal_set_type_id() => __pbn__chosen_goal_set_type_id = null;
        private ulong? __pbn__chosen_goal_set_type_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalChainData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong starting_goal_set_type_id
        {
            get => __pbn__starting_goal_set_type_id.GetValueOrDefault();
            set => __pbn__starting_goal_set_type_id = value;
        }
        public bool ShouldSerializestarting_goal_set_type_id() => __pbn__starting_goal_set_type_id != null;
        public void Resetstarting_goal_set_type_id() => __pbn__starting_goal_set_type_id = null;
        private ulong? __pbn__starting_goal_set_type_id;

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong chosen_goal_set_type_id
        {
            get => __pbn__chosen_goal_set_type_id.GetValueOrDefault();
            set => __pbn__chosen_goal_set_type_id = value;
        }
        public bool ShouldSerializechosen_goal_set_type_id() => __pbn__chosen_goal_set_type_id != null;
        public void Resetchosen_goal_set_type_id() => __pbn__chosen_goal_set_type_id = null;
        private ulong? __pbn__chosen_goal_set_type_id;

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong chain_id
        {
            get => __pbn__chain_id.GetValueOrDefault();
            set => __pbn__chain_id = value;
        }
        public bool ShouldSerializechain_id() => __pbn__chain_id != null;
        public void Resetchain_id() => __pbn__chain_id = null;
        private ulong? __pbn__chain_id;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(-1)]
        public int display_position
        {
            get => __pbn__display_position ?? -1;
            set => __pbn__display_position = value;
        }
        public bool ShouldSerializedisplay_position() => __pbn__display_position != null;
        public void Resetdisplay_position() => __pbn__display_position = null;
        private int? __pbn__display_position;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalTrackerData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public bool has_offered_goals
        {
            get => __pbn__has_offered_goals.GetValueOrDefault();
            set => __pbn__has_offered_goals = value;
        }
        public bool ShouldSerializehas_offered_goals() => __pbn__has_offered_goals != null;
        public void Resethas_offered_goals() => __pbn__has_offered_goals = null;
        private bool? __pbn__has_offered_goals;

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong inherited_target_id
        {
            get => __pbn__inherited_target_id.GetValueOrDefault();
            set => __pbn__inherited_target_id = value;
        }
        public bool ShouldSerializeinherited_target_id() => __pbn__inherited_target_id != null;
        public void Resetinherited_target_id() => __pbn__inherited_target_id = null;
        private ulong? __pbn__inherited_target_id;

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<SituationGoalChainData> chains { get; } = new global::System.Collections.Generic.List<SituationGoalChainData>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<SituationGoalData> minor_goals { get; } = new global::System.Collections.Generic.List<SituationGoalData>();

        [global::ProtoBuf.ProtoMember(5)]
        public SituationGoalData main_goal { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<CompletedSituationGoalData> completed_goals { get; } = new global::System.Collections.Generic.List<CompletedSituationGoalData>();

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(GoalTrackerType.STANDARD_GOAL_TRACKER)]
        public GoalTrackerType goal_tracker_type
        {
            get => __pbn__goal_tracker_type ?? GoalTrackerType.STANDARD_GOAL_TRACKER;
            set => __pbn__goal_tracker_type = value;
        }
        public bool ShouldSerializegoal_tracker_type() => __pbn__goal_tracker_type != null;
        public void Resetgoal_tracker_type() => __pbn__goal_tracker_type = null;
        private GoalTrackerType? __pbn__goal_tracker_type;

        [global::ProtoBuf.ProtoContract()]
        public enum GoalTrackerType
        {
            STANDARD_GOAL_TRACKER = 0,
            DYNAMIC_GOAL_TRACKER = 1,
            SIMPLE_GOAL_TRACKER = 2,
            ACTIVITY_GOAL_TRACKER = 3,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationAssignmentData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong job_type_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint purpose
        {
            get => __pbn__purpose.GetValueOrDefault();
            set => __pbn__purpose = value;
        }
        public bool ShouldSerializepurpose() => __pbn__purpose != null;
        public void Resetpurpose() => __pbn__purpose = null;
        private uint? __pbn__purpose;

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong role_state_type_id
        {
            get => __pbn__role_state_type_id.GetValueOrDefault();
            set => __pbn__role_state_type_id = value;
        }
        public bool ShouldSerializerole_state_type_id() => __pbn__role_state_type_id != null;
        public void Resetrole_state_type_id() => __pbn__role_state_type_id = null;
        private ulong? __pbn__role_state_type_id;

        [global::ProtoBuf.ProtoMember(5)]
        public uint spawning_option
        {
            get => __pbn__spawning_option.GetValueOrDefault();
            set => __pbn__spawning_option = value;
        }
        public bool ShouldSerializespawning_option() => __pbn__spawning_option != null;
        public void Resetspawning_option() => __pbn__spawning_option = null;
        private uint? __pbn__spawning_option;

        [global::ProtoBuf.ProtoMember(6)]
        public uint request_priority
        {
            get => __pbn__request_priority.GetValueOrDefault();
            set => __pbn__request_priority = value;
        }
        public bool ShouldSerializerequest_priority() => __pbn__request_priority != null;
        public void Resetrequest_priority() => __pbn__request_priority = null;
        private uint? __pbn__request_priority;

        [global::ProtoBuf.ProtoMember(7)]
        public bool expectation_preference
        {
            get => __pbn__expectation_preference.GetValueOrDefault();
            set => __pbn__expectation_preference = value;
        }
        public bool ShouldSerializeexpectation_preference() => __pbn__expectation_preference != null;
        public void Resetexpectation_preference() => __pbn__expectation_preference = null;
        private bool? __pbn__expectation_preference;

        [global::ProtoBuf.ProtoMember(8)]
        public bool accept_alternate_sim
        {
            get => __pbn__accept_alternate_sim.GetValueOrDefault();
            set => __pbn__accept_alternate_sim = value;
        }
        public bool ShouldSerializeaccept_alternate_sim() => __pbn__accept_alternate_sim != null;
        public void Resetaccept_alternate_sim() => __pbn__accept_alternate_sim = null;
        private bool? __pbn__accept_alternate_sim;

        [global::ProtoBuf.ProtoMember(9)]
        public uint common_blacklist_categories
        {
            get => __pbn__common_blacklist_categories.GetValueOrDefault();
            set => __pbn__common_blacklist_categories = value;
        }
        public bool ShouldSerializecommon_blacklist_categories() => __pbn__common_blacklist_categories != null;
        public void Resetcommon_blacklist_categories() => __pbn__common_blacklist_categories = null;
        private uint? __pbn__common_blacklist_categories;

        [global::ProtoBuf.ProtoMember(10)]
        public bool elevated_importance_override
        {
            get => __pbn__elevated_importance_override.GetValueOrDefault();
            set => __pbn__elevated_importance_override = value;
        }
        public bool ShouldSerializeelevated_importance_override() => __pbn__elevated_importance_override != null;
        public void Resetelevated_importance_override() => __pbn__elevated_importance_override = null;
        private bool? __pbn__elevated_importance_override;

        [global::ProtoBuf.ProtoMember(11)]
        public bool reservation
        {
            get => __pbn__reservation.GetValueOrDefault();
            set => __pbn__reservation = value;
        }
        public bool ShouldSerializereservation() => __pbn__reservation != null;
        public void Resetreservation() => __pbn__reservation = null;
        private bool? __pbn__reservation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSimpleSeedlingData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint phase_index
        {
            get => __pbn__phase_index.GetValueOrDefault();
            set => __pbn__phase_index = value;
        }
        public bool ShouldSerializephase_index() => __pbn__phase_index != null;
        public void Resetphase_index() => __pbn__phase_index = null;
        private uint? __pbn__phase_index;

        [global::ProtoBuf.ProtoMember(2)]
        public float remaining_phase_time
        {
            get => __pbn__remaining_phase_time.GetValueOrDefault();
            set => __pbn__remaining_phase_time = value;
        }
        public bool ShouldSerializeremaining_phase_time() => __pbn__remaining_phase_time != null;
        public void Resetremaining_phase_time() => __pbn__remaining_phase_time = null;
        private float? __pbn__remaining_phase_time;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationComplexSeedlingData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] situation_custom_data
        {
            get => __pbn__situation_custom_data;
            set => __pbn__situation_custom_data = value;
        }
        public bool ShouldSerializesituation_custom_data() => __pbn__situation_custom_data != null;
        public void Resetsituation_custom_data() => __pbn__situation_custom_data = null;
        private byte[] __pbn__situation_custom_data;

        [global::ProtoBuf.ProtoMember(2)]
        public byte[] state_custom_data
        {
            get => __pbn__state_custom_data;
            set => __pbn__state_custom_data = value;
        }
        public bool ShouldSerializestate_custom_data() => __pbn__state_custom_data != null;
        public void Resetstate_custom_data() => __pbn__state_custom_data = null;
        private byte[] __pbn__state_custom_data;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobAndRoleState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong job_type_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong role_state_type_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong emotional_loot_actions_type_id
        {
            get => __pbn__emotional_loot_actions_type_id.GetValueOrDefault();
            set => __pbn__emotional_loot_actions_type_id = value;
        }
        public bool ShouldSerializeemotional_loot_actions_type_id() => __pbn__emotional_loot_actions_type_id != null;
        public void Resetemotional_loot_actions_type_id() => __pbn__emotional_loot_actions_type_id = null;
        private ulong? __pbn__emotional_loot_actions_type_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSpecialObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong definition_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::EA.Sims4.Network.LocalizedString name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSeedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong situation_type_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong situation_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint seed_purpose
        {
            get => __pbn__seed_purpose.GetValueOrDefault();
            set => __pbn__seed_purpose = value;
        }
        public bool ShouldSerializeseed_purpose() => __pbn__seed_purpose != null;
        public void Resetseed_purpose() => __pbn__seed_purpose = null;
        private uint? __pbn__seed_purpose;

        [global::ProtoBuf.ProtoMember(4)]
        public bool invite_only
        {
            get => __pbn__invite_only.GetValueOrDefault();
            set => __pbn__invite_only = value;
        }
        public bool ShouldSerializeinvite_only() => __pbn__invite_only != null;
        public void Resetinvite_only() => __pbn__invite_only = null;
        private bool? __pbn__invite_only;

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong host_sim_id
        {
            get => __pbn__host_sim_id.GetValueOrDefault();
            set => __pbn__host_sim_id = value;
        }
        public bool ShouldSerializehost_sim_id() => __pbn__host_sim_id != null;
        public void Resethost_sim_id() => __pbn__host_sim_id = null;
        private ulong? __pbn__host_sim_id;

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<SituationAssignmentData> assignments { get; } = new global::System.Collections.Generic.List<SituationAssignmentData>();

        [global::ProtoBuf.ProtoMember(7)]
        public bool user_facing
        {
            get => __pbn__user_facing.GetValueOrDefault();
            set => __pbn__user_facing = value;
        }
        public bool ShouldSerializeuser_facing() => __pbn__user_facing != null;
        public void Resetuser_facing() => __pbn__user_facing = null;
        private bool? __pbn__user_facing;

        [global::ProtoBuf.ProtoMember(8)]
        public float duration
        {
            get => __pbn__duration.GetValueOrDefault();
            set => __pbn__duration = value;
        }
        public bool ShouldSerializeduration() => __pbn__duration != null;
        public void Resetduration() => __pbn__duration = null;
        private float? __pbn__duration;

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<SituationJobAndRoleState> jobs_and_role_states { get; } = new global::System.Collections.Generic.List<SituationJobAndRoleState>();

        [global::ProtoBuf.ProtoMember(11)]
        public ulong create_time
        {
            get => __pbn__create_time.GetValueOrDefault();
            set => __pbn__create_time = value;
        }
        public bool ShouldSerializecreate_time() => __pbn__create_time != null;
        public void Resetcreate_time() => __pbn__create_time = null;
        private ulong? __pbn__create_time;

        [global::ProtoBuf.ProtoMember(12)]
        public float score
        {
            get => __pbn__score.GetValueOrDefault();
            set => __pbn__score = value;
        }
        public bool ShouldSerializescore() => __pbn__score != null;
        public void Resetscore() => __pbn__score = null;
        private float? __pbn__score;

        [global::ProtoBuf.ProtoMember(13)]
        public SituationSimpleSeedlingData simple_data { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public SituationComplexSeedlingData complex_data { get; set; }

        [global::ProtoBuf.ProtoMember(15, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong filter_requesting_sim_id
        {
            get => __pbn__filter_requesting_sim_id.GetValueOrDefault();
            set => __pbn__filter_requesting_sim_id = value;
        }
        public bool ShouldSerializefilter_requesting_sim_id() => __pbn__filter_requesting_sim_id != null;
        public void Resetfilter_requesting_sim_id() => __pbn__filter_requesting_sim_id = null;
        private ulong? __pbn__filter_requesting_sim_id;

        [global::ProtoBuf.ProtoMember(16)]
        public SituationGoalTrackerData goal_tracker_data { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public ulong start_time
        {
            get => __pbn__start_time.GetValueOrDefault();
            set => __pbn__start_time = value;
        }
        public bool ShouldSerializestart_time() => __pbn__start_time != null;
        public void Resetstart_time() => __pbn__start_time = null;
        private ulong? __pbn__start_time;

        [global::ProtoBuf.ProtoMember(18, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong active_household_id
        {
            get => __pbn__active_household_id.GetValueOrDefault();
            set => __pbn__active_household_id = value;
        }
        public bool ShouldSerializeactive_household_id() => __pbn__active_household_id != null;
        public void Resetactive_household_id() => __pbn__active_household_id = null;
        private ulong? __pbn__active_household_id;

        [global::ProtoBuf.ProtoMember(19)]
        public bool scoring_enabled
        {
            get => __pbn__scoring_enabled.GetValueOrDefault();
            set => __pbn__scoring_enabled = value;
        }
        public bool ShouldSerializescoring_enabled() => __pbn__scoring_enabled != null;
        public void Resetscoring_enabled() => __pbn__scoring_enabled = null;
        private bool? __pbn__scoring_enabled;

        [global::ProtoBuf.ProtoMember(20)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool main_goal_visibility
        {
            get => __pbn__main_goal_visibility ?? true;
            set => __pbn__main_goal_visibility = value;
        }
        public bool ShouldSerializemain_goal_visibility() => __pbn__main_goal_visibility != null;
        public void Resetmain_goal_visibility() => __pbn__main_goal_visibility = null;
        private bool? __pbn__main_goal_visibility;

        [global::ProtoBuf.ProtoMember(21, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong linked_sim_id
        {
            get => __pbn__linked_sim_id.GetValueOrDefault();
            set => __pbn__linked_sim_id = value;
        }
        public bool ShouldSerializelinked_sim_id() => __pbn__linked_sim_id != null;
        public void Resetlinked_sim_id() => __pbn__linked_sim_id = null;
        private ulong? __pbn__linked_sim_id;

        [global::ProtoBuf.ProtoMember(22)]
        public global::EA.Sims4.Network.IconInfo special_object_icon { get; set; }

        [global::ProtoBuf.ProtoMember(23, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] situation_activity_ids { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public SituationSpecialObject special_object { get; set; }

        [global::ProtoBuf.ProtoMember(25)]
        public ulong guest_attire_color
        {
            get => __pbn__guest_attire_color.GetValueOrDefault();
            set => __pbn__guest_attire_color = value;
        }
        public bool ShouldSerializeguest_attire_color() => __pbn__guest_attire_color != null;
        public void Resetguest_attire_color() => __pbn__guest_attire_color = null;
        private ulong? __pbn__guest_attire_color;

        [global::ProtoBuf.ProtoMember(26)]
        public ulong guest_attire_style
        {
            get => __pbn__guest_attire_style.GetValueOrDefault();
            set => __pbn__guest_attire_style = value;
        }
        public bool ShouldSerializeguest_attire_style() => __pbn__guest_attire_style != null;
        public void Resetguest_attire_style() => __pbn__guest_attire_style = null;
        private ulong? __pbn__guest_attire_style;

        [global::ProtoBuf.ProtoMember(27)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool spawn_sims_during_zone_spin_up
        {
            get => __pbn__spawn_sims_during_zone_spin_up ?? false;
            set => __pbn__spawn_sims_during_zone_spin_up = value;
        }
        public bool ShouldSerializespawn_sims_during_zone_spin_up() => __pbn__spawn_sims_during_zone_spin_up != null;
        public void Resetspawn_sims_during_zone_spin_up() => __pbn__spawn_sims_during_zone_spin_up = null;
        private bool? __pbn__spawn_sims_during_zone_spin_up;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationBlacklistTagData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong tag { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong time { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationBlacklistData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SituationBlacklistTagData> tag_data { get; } = new global::System.Collections.Generic.List<SituationBlacklistTagData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AllSituationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SituationSeedData> seeds { get; } = new global::System.Collections.Generic.List<SituationSeedData>();

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong leave_situation_id
        {
            get => __pbn__leave_situation_id.GetValueOrDefault();
            set => __pbn__leave_situation_id = value;
        }
        public bool ShouldSerializeleave_situation_id() => __pbn__leave_situation_id != null;
        public void Resetleave_situation_id() => __pbn__leave_situation_id = null;
        private ulong? __pbn__leave_situation_id;

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong leave_now_situation_id
        {
            get => __pbn__leave_now_situation_id.GetValueOrDefault();
            set => __pbn__leave_now_situation_id = value;
        }
        public bool ShouldSerializeleave_now_situation_id() => __pbn__leave_now_situation_id != null;
        public void Resetleave_now_situation_id() => __pbn__leave_now_situation_id = null;
        private ulong? __pbn__leave_now_situation_id;

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<SituationBlacklistData> blacklist_data { get; } = new global::System.Collections.Generic.List<SituationBlacklistData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
