// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Situations.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SimPickerItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool enabled
        {
            get => __pbn__enabled ?? true;
            set => __pbn__enabled = value;
        }
        public bool ShouldSerializeenabled() => __pbn__enabled != null;
        public void Resetenabled() => __pbn__enabled = null;
        private bool? __pbn__enabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationEditJobData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong job_id
        {
            get => __pbn__job_id.GetValueOrDefault();
            set => __pbn__job_id = value;
        }
        public bool ShouldSerializejob_id() => __pbn__job_id != null;
        public void Resetjob_id() => __pbn__job_id = null;
        private ulong? __pbn__job_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] sim_ids { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint hire_count
        {
            get => __pbn__hire_count.GetValueOrDefault();
            set => __pbn__hire_count = value;
        }
        public bool ShouldSerializehire_count() => __pbn__hire_count != null;
        public void Resethire_count() => __pbn__hire_count = null;
        private uint? __pbn__hire_count;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationEditData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong drama_node_id
        {
            get => __pbn__drama_node_id.GetValueOrDefault();
            set => __pbn__drama_node_id = value;
        }
        public bool ShouldSerializedrama_node_id() => __pbn__drama_node_id != null;
        public void Resetdrama_node_id() => __pbn__drama_node_id = null;
        private ulong? __pbn__drama_node_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] selected_activity_ids { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ulong guest_attire_style
        {
            get => __pbn__guest_attire_style.GetValueOrDefault();
            set => __pbn__guest_attire_style = value;
        }
        public bool ShouldSerializeguest_attire_style() => __pbn__guest_attire_style != null;
        public void Resetguest_attire_style() => __pbn__guest_attire_style = null;
        private ulong? __pbn__guest_attire_style;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong guest_attire_color
        {
            get => __pbn__guest_attire_color.GetValueOrDefault();
            set => __pbn__guest_attire_color = value;
        }
        public bool ShouldSerializeguest_attire_color() => __pbn__guest_attire_color != null;
        public void Resetguest_attire_color() => __pbn__guest_attire_color = null;
        private ulong? __pbn__guest_attire_color;

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<SituationEditJobData> job_data { get; } = new global::System.Collections.Generic.List<SituationEditJobData>();

        [global::ProtoBuf.ProtoMember(7)]
        public IconInfo special_object_icon_info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationPrepare : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint situation_session_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool is_targeted
        {
            get => __pbn__is_targeted ?? false;
            set => __pbn__is_targeted = value;
        }
        public bool ShouldSerializeis_targeted() => __pbn__is_targeted != null;
        public void Resetis_targeted() => __pbn__is_targeted = null;
        private bool? __pbn__is_targeted;

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<SimPickerItem> sims { get; } = new global::System.Collections.Generic.List<SimPickerItem>();

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong target_id
        {
            get => __pbn__target_id.GetValueOrDefault();
            set => __pbn__target_id = value;
        }
        public bool ShouldSerializetarget_id() => __pbn__target_id != null;
        public void Resettarget_id() => __pbn__target_id = null;
        private ulong? __pbn__target_id;

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong sim_id
        {
            get => __pbn__sim_id.GetValueOrDefault();
            set => __pbn__sim_id = value;
        }
        public bool ShouldSerializesim_id() => __pbn__sim_id != null;
        public void Resetsim_id() => __pbn__sim_id = null;
        private ulong? __pbn__sim_id;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong[] situation_resource_id { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong creation_time
        {
            get => __pbn__creation_time.GetValueOrDefault();
            set => __pbn__creation_time = value;
        }
        public bool ShouldSerializecreation_time() => __pbn__creation_time != null;
        public void Resetcreation_time() => __pbn__creation_time = null;
        private ulong? __pbn__creation_time;

        [global::ProtoBuf.ProtoMember(8)]
        public SituationEditData edit_data { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint situation_category
        {
            get => __pbn__situation_category.GetValueOrDefault();
            set => __pbn__situation_category = value;
        }
        public bool ShouldSerializesituation_category() => __pbn__situation_category != null;
        public void Resetsituation_category() => __pbn__situation_category = null;
        private uint? __pbn__situation_category;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationIDBatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint situation_session_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] situation_resource_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<LocalizedString> situation_name { get; } = new global::System.Collections.Generic.List<LocalizedString>();

        [global::ProtoBuf.ProtoMember(4)]
        public uint[] category_id { get; set; }

        [global::ProtoBuf.ProtoMember(5, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] mtx_id { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public int[] highest_medal_earned { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool scoring_enabled
        {
            get => __pbn__scoring_enabled.GetValueOrDefault();
            set => __pbn__scoring_enabled = value;
        }
        public bool ShouldSerializescoring_enabled() => __pbn__scoring_enabled != null;
        public void Resetscoring_enabled() => __pbn__scoring_enabled = null;
        private bool? __pbn__scoring_enabled;

        [global::ProtoBuf.ProtoMember(8)]
        public global::System.Collections.Generic.List<LocalizedString> tooltip { get; } = new global::System.Collections.Generic.List<LocalizedString>();

        [global::ProtoBuf.ProtoMember(9)]
        public bool[] allow_user_facing_goals { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<ResourceKey> medal_icon_override { get; } = new global::System.Collections.Generic.List<ResourceKey>();

        [global::ProtoBuf.ProtoMember(11)]
        public global::System.Collections.Generic.List<LocalizedString> scoring_lock_reason { get; } = new global::System.Collections.Generic.List<LocalizedString>();

        [global::ProtoBuf.ProtoMember(12)]
        public bool[] new_entry { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationDataBatch : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint situation_session_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SituationData> situations { get; } = new global::System.Collections.Generic.List<SituationData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGuestAttireColor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong color_tag
        {
            get => __pbn__color_tag.GetValueOrDefault();
            set => __pbn__color_tag = value;
        }
        public bool ShouldSerializecolor_tag() => __pbn__color_tag != null;
        public void Resetcolor_tag() => __pbn__color_tag = null;
        private ulong? __pbn__color_tag;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString color_name { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string color_value
        {
            get => __pbn__color_value ?? "";
            set => __pbn__color_value = value;
        }
        public bool ShouldSerializecolor_value() => __pbn__color_value != null;
        public void Resetcolor_value() => __pbn__color_value = null;
        private string __pbn__color_value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGuestAttireStyle : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong style_tag
        {
            get => __pbn__style_tag.GetValueOrDefault();
            set => __pbn__style_tag = value;
        }
        public bool ShouldSerializestyle_tag() => __pbn__style_tag != null;
        public void Resetstyle_tag() => __pbn__style_tag = null;
        private ulong? __pbn__style_tag;

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString style_name { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationStyleData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SituationGuestAttireColor> guest_attire_colors { get; } = new global::System.Collections.Generic.List<SituationGuestAttireColor>();

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SituationGuestAttireStyle> guest_attire_styles { get; } = new global::System.Collections.Generic.List<SituationGuestAttireStyle>();

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedString special_object_help_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public ResourceKey no_special_object_icon { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public LocalizedString no_special_object_label { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong cas_edit_job_id
        {
            get => __pbn__cas_edit_job_id.GetValueOrDefault();
            set => __pbn__cas_edit_job_id = value;
        }
        public bool ShouldSerializecas_edit_job_id() => __pbn__cas_edit_job_id != null;
        public void Resetcas_edit_job_id() => __pbn__cas_edit_job_id = null;
        private ulong? __pbn__cas_edit_job_id;

        [global::ProtoBuf.ProtoMember(7)]
        public uint cas_edit_outfit_category
        {
            get => __pbn__cas_edit_outfit_category.GetValueOrDefault();
            set => __pbn__cas_edit_outfit_category = value;
        }
        public bool ShouldSerializecas_edit_outfit_category() => __pbn__cas_edit_outfit_category != null;
        public void Resetcas_edit_outfit_category() => __pbn__cas_edit_outfit_category = null;
        private uint? __pbn__cas_edit_outfit_category;

        [global::ProtoBuf.ProtoMember(8)]
        public ResourceKey cas_edit_no_sim_icon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public IconInfo icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint cost { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint max_participants { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<SituationLevelReward> rewards { get; } = new global::System.Collections.Generic.List<SituationLevelReward>();

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<SituationJobData> jobs { get; } = new global::System.Collections.Generic.List<SituationJobData>();

        [global::ProtoBuf.ProtoMember(6)]
        public ulong[] available_activity_ids { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong[] required_activity_ids { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SituationStyleData style_data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong job_resource_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public IconInfo icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public bool is_hireable { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint min_required { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint max_allowed { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint hire_cost
        {
            get => __pbn__hire_cost.GetValueOrDefault();
            set => __pbn__hire_cost = value;
        }
        public bool ShouldSerializehire_cost() => __pbn__hire_cost != null;
        public void Resethire_cost() => __pbn__hire_cost = null;
        private uint? __pbn__hire_cost;

        [global::ProtoBuf.ProtoMember(7)]
        public LocalizedString help_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool is_guest
        {
            get => __pbn__is_guest.GetValueOrDefault();
            set => __pbn__is_guest = value;
        }
        public bool ShouldSerializeis_guest() => __pbn__is_guest != null;
        public void Resetis_guest() => __pbn__is_guest = null;
        private bool? __pbn__is_guest;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationLevelReward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint level { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<LocalizedString> display_name { get; } = new global::System.Collections.Generic.List<LocalizedString>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationAssignJob : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint situation_session_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] sim_ids { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] job_resource_ids { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobSim : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong account_id
        {
            get => __pbn__account_id.GetValueOrDefault();
            set => __pbn__account_id = value;
        }
        public bool ShouldSerializeaccount_id() => __pbn__account_id != null;
        public void Resetaccount_id() => __pbn__account_id = null;
        private ulong? __pbn__account_id;

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong career_id
        {
            get => __pbn__career_id.GetValueOrDefault();
            set => __pbn__career_id = value;
        }
        public bool ShouldSerializecareer_id() => __pbn__career_id != null;
        public void Resetcareer_id() => __pbn__career_id = null;
        private ulong? __pbn__career_id;

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong career_track_id
        {
            get => __pbn__career_track_id.GetValueOrDefault();
            set => __pbn__career_track_id = value;
        }
        public bool ShouldSerializecareer_track_id() => __pbn__career_track_id != null;
        public void Resetcareer_track_id() => __pbn__career_track_id = null;
        private ulong? __pbn__career_track_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobSims : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint situation_session_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong job_resource_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] sim_ids { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool lock_selection
        {
            get => __pbn__lock_selection.GetValueOrDefault();
            set => __pbn__lock_selection = value;
        }
        public bool ShouldSerializelock_selection() => __pbn__lock_selection != null;
        public void Resetlock_selection() => __pbn__lock_selection = null;
        private bool? __pbn__lock_selection;

        [global::ProtoBuf.ProtoMember(5)]
        public global::System.Collections.Generic.List<SituationJobSim> sims { get; } = new global::System.Collections.Generic.List<SituationJobSim>();

        [global::ProtoBuf.ProtoMember(6)]
        public LocalizedString requirements { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationLocations : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<LotInfoItem> situation_locations { get; } = new global::System.Collections.Generic.List<LotInfoItem>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSimScore : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint score { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public IconInfo job_icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint version_id
        {
            get => __pbn__version_id.GetValueOrDefault();
            set => __pbn__version_id = value;
        }
        public bool ShouldSerializeversion_id() => __pbn__version_id != null;
        public void Resetversion_id() => __pbn__version_id = null;
        private uint? __pbn__version_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationLevelData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public LocalizedString description { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint max_threshold { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationLevelUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint score_lower_bound
        {
            get => __pbn__score_lower_bound.GetValueOrDefault();
            set => __pbn__score_lower_bound = value;
        }
        public bool ShouldSerializescore_lower_bound() => __pbn__score_lower_bound != null;
        public void Resetscore_lower_bound() => __pbn__score_lower_bound = null;
        private uint? __pbn__score_lower_bound;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint score_upper_bound { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public uint current_level { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public IconInfo level_icon { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationJobAssignment : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public LocalizedString name { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public LocalizedString desc { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedString tooltip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationStart : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint score { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SituationSimScore> participants { get; } = new global::System.Collections.Generic.List<SituationSimScore>();

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public IconInfo icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<SituationLevelData> level_data { get; } = new global::System.Collections.Generic.List<SituationLevelData>();

        [global::ProtoBuf.ProtoMember(5)]
        public OperationList operation_list { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong end_time
        {
            get => __pbn__end_time.GetValueOrDefault();
            set => __pbn__end_time = value;
        }
        public bool ShouldSerializeend_time() => __pbn__end_time != null;
        public void Resetend_time() => __pbn__end_time = null;
        private ulong? __pbn__end_time;

        [global::ProtoBuf.ProtoMember(7)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(8)]
        public SituationLevelUpdate current_level { get; set; }

        [global::ProtoBuf.ProtoMember(9, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong[] sim_ids { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<SituationJobAssignment> sim_jobs { get; } = new global::System.Collections.Generic.List<SituationJobAssignment>();

        [global::ProtoBuf.ProtoMember(11)]
        public ulong start_time
        {
            get => __pbn__start_time.GetValueOrDefault();
            set => __pbn__start_time = value;
        }
        public bool ShouldSerializestart_time() => __pbn__start_time != null;
        public void Resetstart_time() => __pbn__start_time = null;
        private ulong? __pbn__start_time;

        [global::ProtoBuf.ProtoMember(12)]
        public ResourceKey start_audio_sting { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public bool scoring_enabled
        {
            get => __pbn__scoring_enabled.GetValueOrDefault();
            set => __pbn__scoring_enabled = value;
        }
        public bool ShouldSerializescoring_enabled() => __pbn__scoring_enabled != null;
        public void Resetscoring_enabled() => __pbn__scoring_enabled = null;
        private bool? __pbn__scoring_enabled;

        [global::ProtoBuf.ProtoMember(14)]
        public bool is_active_career
        {
            get => __pbn__is_active_career.GetValueOrDefault();
            set => __pbn__is_active_career = value;
        }
        public bool ShouldSerializeis_active_career() => __pbn__is_active_career != null;
        public void Resetis_active_career() => __pbn__is_active_career = null;
        private bool? __pbn__is_active_career;

        [global::ProtoBuf.ProtoMember(15)]
        public bool has_stayed_late
        {
            get => __pbn__has_stayed_late.GetValueOrDefault();
            set => __pbn__has_stayed_late = value;
        }
        public bool ShouldSerializehas_stayed_late() => __pbn__has_stayed_late != null;
        public void Resethas_stayed_late() => __pbn__has_stayed_late = null;
        private bool? __pbn__has_stayed_late;

        [global::ProtoBuf.ProtoMember(16)]
        public global::System.Collections.Generic.List<SituationMeterData> meter_data { get; } = new global::System.Collections.Generic.List<SituationMeterData>();

        [global::ProtoBuf.ProtoMember(17)]
        public uint display_type
        {
            get => __pbn__display_type.GetValueOrDefault();
            set => __pbn__display_type = value;
        }
        public bool ShouldSerializedisplay_type() => __pbn__display_type != null;
        public void Resetdisplay_type() => __pbn__display_type = null;
        private uint? __pbn__display_type;

        [global::ProtoBuf.ProtoMember(18, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong linked_sim_id
        {
            get => __pbn__linked_sim_id.GetValueOrDefault();
            set => __pbn__linked_sim_id = value;
        }
        public bool ShouldSerializelinked_sim_id() => __pbn__linked_sim_id != null;
        public void Resetlinked_sim_id() => __pbn__linked_sim_id = null;
        private ulong? __pbn__linked_sim_id;

        [global::ProtoBuf.ProtoMember(19)]
        public bool force_goals_enabled
        {
            get => __pbn__force_goals_enabled.GetValueOrDefault();
            set => __pbn__force_goals_enabled = value;
        }
        public bool ShouldSerializeforce_goals_enabled() => __pbn__force_goals_enabled != null;
        public void Resetforce_goals_enabled() => __pbn__force_goals_enabled = null;
        private bool? __pbn__force_goals_enabled;

        [global::ProtoBuf.ProtoMember(20)]
        public uint user_facing_type
        {
            get => __pbn__user_facing_type.GetValueOrDefault();
            set => __pbn__user_facing_type = value;
        }
        public bool ShouldSerializeuser_facing_type() => __pbn__user_facing_type != null;
        public void Resetuser_facing_type() => __pbn__user_facing_type = null;
        private uint? __pbn__user_facing_type;

        [global::ProtoBuf.ProtoMember(21)]
        public bool allow_non_prestige_events
        {
            get => __pbn__allow_non_prestige_events.GetValueOrDefault();
            set => __pbn__allow_non_prestige_events = value;
        }
        public bool ShouldSerializeallow_non_prestige_events() => __pbn__allow_non_prestige_events != null;
        public void Resetallow_non_prestige_events() => __pbn__allow_non_prestige_events = null;
        private bool? __pbn__allow_non_prestige_events;

        [global::ProtoBuf.ProtoMember(22)]
        public uint display_priority
        {
            get => __pbn__display_priority.GetValueOrDefault();
            set => __pbn__display_priority = value;
        }
        public bool ShouldSerializedisplay_priority() => __pbn__display_priority != null;
        public void Resetdisplay_priority() => __pbn__display_priority = null;
        private uint? __pbn__display_priority;

        [global::ProtoBuf.ProtoMember(23)]
        public ulong display_delay
        {
            get => __pbn__display_delay.GetValueOrDefault();
            set => __pbn__display_delay = value;
        }
        public bool ShouldSerializedisplay_delay() => __pbn__display_delay != null;
        public void Resetdisplay_delay() => __pbn__display_delay = null;
        private ulong? __pbn__display_delay;

        [global::ProtoBuf.ProtoMember(24)]
        public bool from_load
        {
            get => __pbn__from_load.GetValueOrDefault();
            set => __pbn__from_load = value;
        }
        public bool ShouldSerializefrom_load() => __pbn__from_load != null;
        public void Resetfrom_load() => __pbn__from_load = null;
        private bool? __pbn__from_load;

        [global::ProtoBuf.ProtoMember(25)]
        public ulong situation_guid
        {
            get => __pbn__situation_guid.GetValueOrDefault();
            set => __pbn__situation_guid = value;
        }
        public bool ShouldSerializesituation_guid() => __pbn__situation_guid != null;
        public void Resetsituation_guid() => __pbn__situation_guid = null;
        private ulong? __pbn__situation_guid;

        [global::ProtoBuf.ProtoMember(26)]
        public ResourceKey background_audio { get; set; }

        [global::ProtoBuf.ProtoMember(27)]
        public uint situation_display_flags
        {
            get => __pbn__situation_display_flags.GetValueOrDefault();
            set => __pbn__situation_display_flags = value;
        }
        public bool ShouldSerializesituation_display_flags() => __pbn__situation_display_flags != null;
        public void Resetsituation_display_flags() => __pbn__situation_display_flags = null;
        private uint? __pbn__situation_display_flags;

        [global::ProtoBuf.ProtoMember(28)]
        public uint situation_display_style
        {
            get => __pbn__situation_display_style.GetValueOrDefault();
            set => __pbn__situation_display_style = value;
        }
        public bool ShouldSerializesituation_display_style() => __pbn__situation_display_style != null;
        public void Resetsituation_display_style() => __pbn__situation_display_style = null;
        private uint? __pbn__situation_display_style;

        [global::ProtoBuf.ProtoMember(29)]
        public LocalizedString situation_end_time_string { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public LocalizedString cancel_tooltip_override { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSimJoined : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong sim_id
        {
            get => __pbn__sim_id.GetValueOrDefault();
            set => __pbn__sim_id = value;
        }
        public bool ShouldSerializesim_id() => __pbn__sim_id != null;
        public void Resetsim_id() => __pbn__sim_id = null;
        private ulong? __pbn__sim_id;

        [global::ProtoBuf.ProtoMember(2)]
        public SituationJobAssignment job_assignment { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationSimLeft : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong sim_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationScoreUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint score { get; set; }

        [global::ProtoBuf.ProtoMember(4, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong sim_id
        {
            get => __pbn__sim_id.GetValueOrDefault();
            set => __pbn__sim_id = value;
        }
        public bool ShouldSerializesim_id() => __pbn__sim_id != null;
        public void Resetsim_id() => __pbn__sim_id = null;
        private ulong? __pbn__sim_id;

        [global::ProtoBuf.ProtoMember(5)]
        public SituationLevelUpdate current_level { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint goal_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public IconInfo icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedString goal_name { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint max_iterations
        {
            get => __pbn__max_iterations.GetValueOrDefault();
            set => __pbn__max_iterations = value;
        }
        public bool ShouldSerializemax_iterations() => __pbn__max_iterations != null;
        public void Resetmax_iterations() => __pbn__max_iterations = null;
        private uint? __pbn__max_iterations;

        [global::ProtoBuf.ProtoMember(5)]
        public uint current_iterations
        {
            get => __pbn__current_iterations.GetValueOrDefault();
            set => __pbn__current_iterations = value;
        }
        public bool ShouldSerializecurrent_iterations() => __pbn__current_iterations != null;
        public void Resetcurrent_iterations() => __pbn__current_iterations = null;
        private uint? __pbn__current_iterations;

        [global::ProtoBuf.ProtoMember(6)]
        public LocalizedString goal_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ResourceKey audio_sting { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public uint display_type
        {
            get => __pbn__display_type.GetValueOrDefault();
            set => __pbn__display_type = value;
        }
        public bool ShouldSerializedisplay_type() => __pbn__display_type != null;
        public void Resetdisplay_type() => __pbn__display_type = null;
        private uint? __pbn__display_type;

        [global::ProtoBuf.ProtoMember(9)]
        public bool highlight_goal
        {
            get => __pbn__highlight_goal.GetValueOrDefault();
            set => __pbn__highlight_goal = value;
        }
        public bool ShouldSerializehighlight_goal() => __pbn__highlight_goal != null;
        public void Resethighlight_goal() => __pbn__highlight_goal = null;
        private bool? __pbn__highlight_goal;

        [global::ProtoBuf.ProtoMember(10)]
        public uint goal_preference
        {
            get => __pbn__goal_preference.GetValueOrDefault();
            set => __pbn__goal_preference = value;
        }
        public bool ShouldSerializegoal_preference() => __pbn__goal_preference != null;
        public void Resetgoal_preference() => __pbn__goal_preference = null;
        private uint? __pbn__goal_preference;

        [global::ProtoBuf.ProtoMember(11)]
        public LocalizedString goal_preference_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public IconInfo secondary_icon_info { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public ulong tutorial_tip_group_guid
        {
            get => __pbn__tutorial_tip_group_guid.GetValueOrDefault();
            set => __pbn__tutorial_tip_group_guid = value;
        }
        public bool ShouldSerializetutorial_tip_group_guid() => __pbn__tutorial_tip_group_guid != null;
        public void Resettutorial_tip_group_guid() => __pbn__tutorial_tip_group_guid = null;
        private ulong? __pbn__tutorial_tip_group_guid;

        [global::ProtoBuf.ProtoMember(14)]
        public bool is_complete
        {
            get => __pbn__is_complete.GetValueOrDefault();
            set => __pbn__is_complete = value;
        }
        public bool ShouldSerializeis_complete() => __pbn__is_complete != null;
        public void Resetis_complete() => __pbn__is_complete = null;
        private bool? __pbn__is_complete;

        [global::ProtoBuf.ProtoMember(15)]
        public bool is_mandatory
        {
            get => __pbn__is_mandatory.GetValueOrDefault();
            set => __pbn__is_mandatory = value;
        }
        public bool ShouldSerializeis_mandatory() => __pbn__is_mandatory != null;
        public void Resetis_mandatory() => __pbn__is_mandatory = null;
        private bool? __pbn__is_mandatory;

        [global::ProtoBuf.ProtoMember(16)]
        public ulong expiration_time
        {
            get => __pbn__expiration_time.GetValueOrDefault();
            set => __pbn__expiration_time = value;
        }
        public bool ShouldSerializeexpiration_time() => __pbn__expiration_time != null;
        public void Resetexpiration_time() => __pbn__expiration_time = null;
        private ulong? __pbn__expiration_time;

        [global::ProtoBuf.ProtoMember(17)]
        public ulong ui_element
        {
            get => __pbn__ui_element.GetValueOrDefault();
            set => __pbn__ui_element = value;
        }
        public bool ShouldSerializeui_element() => __pbn__ui_element != null;
        public void Resetui_element() => __pbn__ui_element = null;
        private ulong? __pbn__ui_element;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalsUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<SituationGoal> goals { get; } = new global::System.Collections.Generic.List<SituationGoal>();

        [global::ProtoBuf.ProtoMember(4)]
        public uint completed_goal_id
        {
            get => __pbn__completed_goal_id.GetValueOrDefault();
            set => __pbn__completed_goal_id = value;
        }
        public bool ShouldSerializecompleted_goal_id() => __pbn__completed_goal_id != null;
        public void Resetcompleted_goal_id() => __pbn__completed_goal_id = null;
        private uint? __pbn__completed_goal_id;

        [global::ProtoBuf.ProtoMember(5)]
        public SituationGoal major_goal { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint goal_status
        {
            get => __pbn__goal_status.GetValueOrDefault();
            set => __pbn__goal_status = value;
        }
        public bool ShouldSerializegoal_status() => __pbn__goal_status != null;
        public void Resetgoal_status() => __pbn__goal_status = null;
        private uint? __pbn__goal_status;

        [global::ProtoBuf.ProtoMember(7)]
        public LocalizedString goal_sub_text { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public SituationGoalButtonData goal_button_data { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationGoalButtonData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LocalizedString button_text { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public bool is_enabled
        {
            get => __pbn__is_enabled.GetValueOrDefault();
            set => __pbn__is_enabled = value;
        }
        public bool ShouldSerializeis_enabled() => __pbn__is_enabled != null;
        public void Resetis_enabled() => __pbn__is_enabled = null;
        private bool? __pbn__is_enabled;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationTimeUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong end_time
        {
            get => __pbn__end_time.GetValueOrDefault();
            set => __pbn__end_time = value;
        }
        public bool ShouldSerializeend_time() => __pbn__end_time != null;
        public void Resetend_time() => __pbn__end_time = null;
        private ulong? __pbn__end_time;

        [global::ProtoBuf.ProtoMember(3)]
        public bool has_stayed_late
        {
            get => __pbn__has_stayed_late.GetValueOrDefault();
            set => __pbn__has_stayed_late = value;
        }
        public bool ShouldSerializehas_stayed_late() => __pbn__has_stayed_late != null;
        public void Resethas_stayed_late() => __pbn__has_stayed_late = null;
        private bool? __pbn__has_stayed_late;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationCallbackResponse : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string situation_callback
        {
            get => __pbn__situation_callback ?? "";
            set => __pbn__situation_callback = value;
        }
        public bool ShouldSerializesituation_callback() => __pbn__situation_callback != null;
        public void Resetsituation_callback() => __pbn__situation_callback = null;
        private string __pbn__situation_callback;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationIconUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(2)]
        public IconInfo icon_info { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationMeterData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint meter_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint minimum_value
        {
            get => __pbn__minimum_value.GetValueOrDefault();
            set => __pbn__minimum_value = value;
        }
        public bool ShouldSerializeminimum_value() => __pbn__minimum_value != null;
        public void Resetminimum_value() => __pbn__minimum_value = null;
        private uint? __pbn__minimum_value;

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint maximum_value
        {
            get => __pbn__maximum_value.GetValueOrDefault();
            set => __pbn__maximum_value = value;
        }
        public bool ShouldSerializemaximum_value() => __pbn__maximum_value != null;
        public void Resetmaximum_value() => __pbn__maximum_value = null;
        private uint? __pbn__maximum_value;

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedString meter_text { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public LocalizedString meter_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public global::System.Collections.Generic.List<SituationMeterThreshold> thresholds { get; } = new global::System.Collections.Generic.List<SituationMeterThreshold>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationMeterThreshold : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public uint threshold { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint color
        {
            get => __pbn__color.GetValueOrDefault();
            set => __pbn__color = value;
        }
        public bool ShouldSerializecolor() => __pbn__color != null;
        public void Resetcolor() => __pbn__color = null;
        private uint? __pbn__color;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationMeterUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong situation_id
        {
            get => __pbn__situation_id.GetValueOrDefault();
            set => __pbn__situation_id = value;
        }
        public bool ShouldSerializesituation_id() => __pbn__situation_id != null;
        public void Resetsituation_id() => __pbn__situation_id = null;
        private ulong? __pbn__situation_id;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint meter_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint update_value
        {
            get => __pbn__update_value.GetValueOrDefault();
            set => __pbn__update_value = value;
        }
        public bool ShouldSerializeupdate_value() => __pbn__update_value != null;
        public void Resetupdate_value() => __pbn__update_value = null;
        private uint? __pbn__update_value;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SituationOutcomeData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LocalizedString situation_name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString outcome_title { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedString outcome_description { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedString next_steps_description { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ResourceKey reward_1_icon { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public LocalizedString reward_1_name { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public LocalizedString reward_1_tooltip { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioGoalGroup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public IconInfo header_icon { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString header_name { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<SituationGoal> goals { get; } = new global::System.Collections.Generic.List<SituationGoal>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioGoalsUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong scenario_id
        {
            get => __pbn__scenario_id.GetValueOrDefault();
            set => __pbn__scenario_id = value;
        }
        public bool ShouldSerializescenario_id() => __pbn__scenario_id != null;
        public void Resetscenario_id() => __pbn__scenario_id = null;
        private ulong? __pbn__scenario_id;

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<ScenarioGoalGroup> goal_groups { get; } = new global::System.Collections.Generic.List<ScenarioGoalGroup>();

        [global::ProtoBuf.ProtoMember(3)]
        public uint completed_goal_id
        {
            get => __pbn__completed_goal_id.GetValueOrDefault();
            set => __pbn__completed_goal_id = value;
        }
        public bool ShouldSerializecompleted_goal_id() => __pbn__completed_goal_id != null;
        public void Resetcompleted_goal_id() => __pbn__completed_goal_id = null;
        private uint? __pbn__completed_goal_id;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong instance_id
        {
            get => __pbn__instance_id.GetValueOrDefault();
            set => __pbn__instance_id = value;
        }
        public bool ShouldSerializeinstance_id() => __pbn__instance_id != null;
        public void Resetinstance_id() => __pbn__instance_id = null;
        private ulong? __pbn__instance_id;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioEnded : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong scenario_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScenarioOutcomeData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LocalizedString scenario_name { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public LocalizedString outcome_title { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public LocalizedString outcome_description { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public LocalizedString next_steps_description { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ResourceKey outcome_icon { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ResourceKey reward_icon { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ResourceKey bonus_icon { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public ulong household_id
        {
            get => __pbn__household_id.GetValueOrDefault();
            set => __pbn__household_id = value;
        }
        public bool ShouldSerializehousehold_id() => __pbn__household_id != null;
        public void Resethousehold_id() => __pbn__household_id = null;
        private ulong? __pbn__household_id;

        [global::ProtoBuf.ProtoMember(9)]
        public LocalizedString reward_tooltip { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public LocalizedString bonus_tooltip { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
