// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Animation.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationEventHandler : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint event_type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint event_id { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong tag { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationRequestBlock : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public byte[] arb_data { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<AnimationEventHandler> event_handlers { get; } = new global::System.Collections.Generic.List<AnimationEventHandler>();

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ManagerObjectId> objects_to_reset { get; } = new global::System.Collections.Generic.List<ManagerObjectId>();

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool is_interruptible
        {
            get => __pbn__is_interruptible ?? false;
            set => __pbn__is_interruptible = value;
        }
        public bool ShouldSerializeis_interruptible() => __pbn__is_interruptible != null;
        public void Resetis_interruptible() => __pbn__is_interruptible = null;
        private bool? __pbn__is_interruptible;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool should_analyze
        {
            get => __pbn__should_analyze ?? false;
            set => __pbn__should_analyze = value;
        }
        public bool ShouldSerializeshould_analyze() => __pbn__should_analyze != null;
        public void Resetshould_analyze() => __pbn__should_analyze = null;
        private bool? __pbn__should_analyze;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AnimationStateRequest : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ResourceKey asm { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string state_name
        {
            get => __pbn__state_name ?? "";
            set => __pbn__state_name = value;
        }
        public bool ShouldSerializestate_name() => __pbn__state_name != null;
        public void Resetstate_name() => __pbn__state_name = null;
        private string __pbn__state_name;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string actor_name
        {
            get => __pbn__actor_name ?? "";
            set => __pbn__actor_name = value;
        }
        public bool ShouldSerializeactor_name() => __pbn__actor_name != null;
        public void Resetactor_name() => __pbn__actor_name = null;
        private string __pbn__actor_name;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CurveData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public float input_value { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float output_value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class FocusEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public EventType type { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint id
        {
            get => __pbn__id.GetValueOrDefault();
            set => __pbn__id = value;
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private uint? __pbn__id;

        [global::ProtoBuf.ProtoMember(3)]
        public uint layer
        {
            get => __pbn__layer.GetValueOrDefault();
            set => __pbn__layer = value;
        }
        public bool ShouldSerializelayer() => __pbn__layer != null;
        public void Resetlayer() => __pbn__layer = null;
        private uint? __pbn__layer;

        [global::ProtoBuf.ProtoMember(4)]
        public uint flags
        {
            get => __pbn__flags.GetValueOrDefault();
            set => __pbn__flags = value;
        }
        public bool ShouldSerializeflags() => __pbn__flags != null;
        public void Resetflags() => __pbn__flags = null;
        private uint? __pbn__flags;

        [global::ProtoBuf.ProtoMember(5)]
        public float score
        {
            get => __pbn__score.GetValueOrDefault();
            set => __pbn__score = value;
        }
        public bool ShouldSerializescore() => __pbn__score != null;
        public void Resetscore() => __pbn__score = null;
        private float? __pbn__score;

        [global::ProtoBuf.ProtoMember(6)]
        public uint joint_name_hash
        {
            get => __pbn__joint_name_hash.GetValueOrDefault();
            set => __pbn__joint_name_hash = value;
        }
        public bool ShouldSerializejoint_name_hash() => __pbn__joint_name_hash != null;
        public void Resetjoint_name_hash() => __pbn__joint_name_hash = null;
        private uint? __pbn__joint_name_hash;

        [global::ProtoBuf.ProtoMember(7)]
        public ulong target_id
        {
            get => __pbn__target_id.GetValueOrDefault();
            set => __pbn__target_id = value;
        }
        public bool ShouldSerializetarget_id() => __pbn__target_id != null;
        public void Resettarget_id() => __pbn__target_id = null;
        private ulong? __pbn__target_id;

        [global::ProtoBuf.ProtoMember(8)]
        public Vector3 offset { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public global::System.Collections.Generic.List<CurveData> distance_curve { get; } = new global::System.Collections.Generic.List<CurveData>();

        [global::ProtoBuf.ProtoMember(10)]
        public global::System.Collections.Generic.List<CurveData> facing_curve { get; } = new global::System.Collections.Generic.List<CurveData>();

        [global::ProtoBuf.ProtoMember(11)]
        public ulong source_id
        {
            get => __pbn__source_id.GetValueOrDefault();
            set => __pbn__source_id = value;
        }
        public bool ShouldSerializesource_id() => __pbn__source_id != null;
        public void Resetsource_id() => __pbn__source_id = null;
        private ulong? __pbn__source_id;

        [global::ProtoBuf.ProtoContract()]
        public enum EventType
        {
            FOCUS_ADD = 0,
            FOCUS_DELETE = 1,
            FOCUS_CLEAR = 2,
            FOCUS_MODIFY_SCORE = 3,
            FOCUS_DISABLE = 4,
            FOCUS_FORCE_UPDATE = 5,
            FOCUS_PRINT = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConfigureAwarenessActor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<AwarenessChannelName> channels_to_remove { get; } = new global::System.Collections.Generic.List<AwarenessChannelName>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<ChannelOptions> channels_to_configure { get; } = new global::System.Collections.Generic.List<ChannelOptions>();

        [global::ProtoBuf.ProtoMember(5)]
        public float proximity_inner_radius
        {
            get => __pbn__proximity_inner_radius.GetValueOrDefault();
            set => __pbn__proximity_inner_radius = value;
        }
        public bool ShouldSerializeproximity_inner_radius() => __pbn__proximity_inner_radius != null;
        public void Resetproximity_inner_radius() => __pbn__proximity_inner_radius = null;
        private float? __pbn__proximity_inner_radius;

        [global::ProtoBuf.ProtoMember(6)]
        public float proximity_outer_radius
        {
            get => __pbn__proximity_outer_radius.GetValueOrDefault();
            set => __pbn__proximity_outer_radius = value;
        }
        public bool ShouldSerializeproximity_outer_radius() => __pbn__proximity_outer_radius != null;
        public void Resetproximity_outer_radius() => __pbn__proximity_outer_radius = null;
        private float? __pbn__proximity_outer_radius;

        [global::ProtoBuf.ProtoContract()]
        public partial class ChannelOptions : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public AwarenessChannelName name { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            [global::System.ComponentModel.DefaultValue(ConfigureAwarenessActor.ChannelEvaluationMode.AWARENESS_CHANNEL_EVALMODE_PEAK)]
            public ConfigureAwarenessActor.ChannelEvaluationMode eval_mode
            {
                get => __pbn__eval_mode ?? ConfigureAwarenessActor.ChannelEvaluationMode.AWARENESS_CHANNEL_EVALMODE_PEAK;
                set => __pbn__eval_mode = value;
            }
            public bool ShouldSerializeeval_mode() => __pbn__eval_mode != null;
            public void Reseteval_mode() => __pbn__eval_mode = null;
            private ConfigureAwarenessActor.ChannelEvaluationMode? __pbn__eval_mode;

            [global::ProtoBuf.ProtoMember(3)]
            public float gate
            {
                get => __pbn__gate.GetValueOrDefault();
                set => __pbn__gate = value;
            }
            public bool ShouldSerializegate() => __pbn__gate != null;
            public void Resetgate() => __pbn__gate = null;
            private float? __pbn__gate;

            [global::ProtoBuf.ProtoMember(4)]
            public float gain
            {
                get => __pbn__gain.GetValueOrDefault();
                set => __pbn__gain = value;
            }
            public bool ShouldSerializegain() => __pbn__gain != null;
            public void Resetgain() => __pbn__gain = null;
            private float? __pbn__gain;

            [global::ProtoBuf.ProtoMember(5)]
            public float limit
            {
                get => __pbn__limit.GetValueOrDefault();
                set => __pbn__limit = value;
            }
            public bool ShouldSerializelimit() => __pbn__limit != null;
            public void Resetlimit() => __pbn__limit = null;
            private float? __pbn__limit;

            [global::ProtoBuf.ProtoMember(6)]
            public float trigger_threshold_delta
            {
                get => __pbn__trigger_threshold_delta.GetValueOrDefault();
                set => __pbn__trigger_threshold_delta = value;
            }
            public bool ShouldSerializetrigger_threshold_delta() => __pbn__trigger_threshold_delta != null;
            public void Resettrigger_threshold_delta() => __pbn__trigger_threshold_delta = null;
            private float? __pbn__trigger_threshold_delta;

            [global::ProtoBuf.ProtoMember(7)]
            [global::System.ComponentModel.DefaultValue("")]
            public string type_name
            {
                get => __pbn__type_name ?? "";
                set => __pbn__type_name = value;
            }
            public bool ShouldSerializetype_name() => __pbn__type_name != null;
            public void Resettype_name() => __pbn__type_name = null;
            private string __pbn__type_name;

            [global::ProtoBuf.ProtoMember(8)]
            [global::System.ComponentModel.DefaultValue(1.5f)]
            public float hold_time
            {
                get => __pbn__hold_time ?? 1.5f;
                set => __pbn__hold_time = value;
            }
            public bool ShouldSerializehold_time() => __pbn__hold_time != null;
            public void Resethold_time() => __pbn__hold_time = null;
            private float? __pbn__hold_time;

            [global::ProtoBuf.ProtoMember(9)]
            [global::System.ComponentModel.DefaultValue(1.5f)]
            public float cool_down_time
            {
                get => __pbn__cool_down_time ?? 1.5f;
                set => __pbn__cool_down_time = value;
            }
            public bool ShouldSerializecool_down_time() => __pbn__cool_down_time != null;
            public void Resetcool_down_time() => __pbn__cool_down_time = null;
            private float? __pbn__cool_down_time;

        }

        [global::ProtoBuf.ProtoContract()]
        public enum ChannelEvaluationMode
        {
            AWARENESS_CHANNEL_EVALMODE_PEAK = 0,
            AWARENESS_CHANNEL_EVALMODE_AVERAGE = 1,
            AWARENESS_CHANNEL_EVALMODE_SUM = 2,
            AWARENESS_CHANNEL_EVALMODE_SUM_SPLITSIGN = 3,
            AWARENESS_CHANNEL_EVALMODE_AVERAGE_SPLITSIGN = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConfigureAwarenessSourceObject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<GameplayChannelValue> gameplay_channel_values { get; } = new global::System.Collections.Generic.List<GameplayChannelValue>();

        [global::ProtoBuf.ProtoMember(4)]
        public float audio_volume_multiplier
        {
            get => __pbn__audio_volume_multiplier.GetValueOrDefault();
            set => __pbn__audio_volume_multiplier = value;
        }
        public bool ShouldSerializeaudio_volume_multiplier() => __pbn__audio_volume_multiplier != null;
        public void Resetaudio_volume_multiplier() => __pbn__audio_volume_multiplier = null;
        private float? __pbn__audio_volume_multiplier;

        [global::ProtoBuf.ProtoMember(5)]
        public float audio_full_volume_radius
        {
            get => __pbn__audio_full_volume_radius.GetValueOrDefault();
            set => __pbn__audio_full_volume_radius = value;
        }
        public bool ShouldSerializeaudio_full_volume_radius() => __pbn__audio_full_volume_radius != null;
        public void Resetaudio_full_volume_radius() => __pbn__audio_full_volume_radius = null;
        private float? __pbn__audio_full_volume_radius;

        [global::ProtoBuf.ProtoMember(6)]
        public float audio_falloff_radius
        {
            get => __pbn__audio_falloff_radius.GetValueOrDefault();
            set => __pbn__audio_falloff_radius = value;
        }
        public bool ShouldSerializeaudio_falloff_radius() => __pbn__audio_falloff_radius != null;
        public void Resetaudio_falloff_radius() => __pbn__audio_falloff_radius = null;
        private float? __pbn__audio_falloff_radius;

        [global::ProtoBuf.ProtoContract()]
        public partial class GameplayChannelValue : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public AwarenessChannelName name { get; set; }

            [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
            public float value { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralControl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint control_id
        {
            get => __pbn__control_id.GetValueOrDefault();
            set => __pbn__control_id = value;
        }
        public bool ShouldSerializecontrol_id() => __pbn__control_id != null;
        public void Resetcontrol_id() => __pbn__control_id = null;
        private uint? __pbn__control_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(ProceduralControlType.UNKNOWN)]
        public ProceduralControlType control_type
        {
            get => __pbn__control_type ?? ProceduralControlType.UNKNOWN;
            set => __pbn__control_type = value;
        }
        public bool ShouldSerializecontrol_type() => __pbn__control_type != null;
        public void Resetcontrol_type() => __pbn__control_type = null;
        private ProceduralControlType? __pbn__control_type;

        [global::ProtoBuf.ProtoMember(3)]
        public uint joint_name_hash
        {
            get => __pbn__joint_name_hash.GetValueOrDefault();
            set => __pbn__joint_name_hash = value;
        }
        public bool ShouldSerializejoint_name_hash() => __pbn__joint_name_hash != null;
        public void Resetjoint_name_hash() => __pbn__joint_name_hash = null;
        private uint? __pbn__joint_name_hash;

        [global::ProtoBuf.ProtoMember(4)]
        public uint reference_joint_name_hash
        {
            get => __pbn__reference_joint_name_hash.GetValueOrDefault();
            set => __pbn__reference_joint_name_hash = value;
        }
        public bool ShouldSerializereference_joint_name_hash() => __pbn__reference_joint_name_hash != null;
        public void Resetreference_joint_name_hash() => __pbn__reference_joint_name_hash = null;
        private uint? __pbn__reference_joint_name_hash;

        [global::ProtoBuf.ProtoMember(5)]
        public bool enable_terrain_alignment
        {
            get => __pbn__enable_terrain_alignment.GetValueOrDefault();
            set => __pbn__enable_terrain_alignment = value;
        }
        public bool ShouldSerializeenable_terrain_alignment() => __pbn__enable_terrain_alignment != null;
        public void Resetenable_terrain_alignment() => __pbn__enable_terrain_alignment = null;
        private bool? __pbn__enable_terrain_alignment;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string bump_sound_name
        {
            get => __pbn__bump_sound_name ?? "";
            set => __pbn__bump_sound_name = value;
        }
        public bool ShouldSerializebump_sound_name() => __pbn__bump_sound_name != null;
        public void Resetbump_sound_name() => __pbn__bump_sound_name = null;
        private string __pbn__bump_sound_name;

        [global::ProtoBuf.ProtoMember(7)]
        public Vector3 dimensions { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string start_vfx
        {
            get => __pbn__start_vfx ?? "";
            set => __pbn__start_vfx = value;
        }
        public bool ShouldSerializestart_vfx() => __pbn__start_vfx != null;
        public void Resetstart_vfx() => __pbn__start_vfx = null;
        private string __pbn__start_vfx;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string stop_vfx
        {
            get => __pbn__stop_vfx ?? "";
            set => __pbn__stop_vfx = value;
        }
        public bool ShouldSerializestop_vfx() => __pbn__stop_vfx != null;
        public void Resetstop_vfx() => __pbn__stop_vfx = null;
        private string __pbn__stop_vfx;

        [global::ProtoBuf.ProtoMember(10)]
        [global::System.ComponentModel.DefaultValue("")]
        public string start_sound
        {
            get => __pbn__start_sound ?? "";
            set => __pbn__start_sound = value;
        }
        public bool ShouldSerializestart_sound() => __pbn__start_sound != null;
        public void Resetstart_sound() => __pbn__start_sound = null;
        private string __pbn__start_sound;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue("")]
        public string loop_sound
        {
            get => __pbn__loop_sound ?? "";
            set => __pbn__loop_sound = value;
        }
        public bool ShouldSerializeloop_sound() => __pbn__loop_sound != null;
        public void Resetloop_sound() => __pbn__loop_sound = null;
        private string __pbn__loop_sound;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string stop_sound
        {
            get => __pbn__stop_sound ?? "";
            set => __pbn__stop_sound = value;
        }
        public bool ShouldSerializestop_sound() => __pbn__stop_sound != null;
        public void Resetstop_sound() => __pbn__stop_sound = null;
        private string __pbn__stop_sound;

        [global::ProtoBuf.ProtoMember(13)]
        public uint vfx_joint_name_hash
        {
            get => __pbn__vfx_joint_name_hash.GetValueOrDefault();
            set => __pbn__vfx_joint_name_hash = value;
        }
        public bool ShouldSerializevfx_joint_name_hash() => __pbn__vfx_joint_name_hash != null;
        public void Resetvfx_joint_name_hash() => __pbn__vfx_joint_name_hash = null;
        private uint? __pbn__vfx_joint_name_hash;

        [global::ProtoBuf.ProtoMember(14)]
        public float effect_speed_threshold
        {
            get => __pbn__effect_speed_threshold.GetValueOrDefault();
            set => __pbn__effect_speed_threshold = value;
        }
        public bool ShouldSerializeeffect_speed_threshold() => __pbn__effect_speed_threshold != null;
        public void Reseteffect_speed_threshold() => __pbn__effect_speed_threshold = null;
        private float? __pbn__effect_speed_threshold;

        [global::ProtoBuf.ProtoContract()]
        public enum ProceduralControlType
        {
            UNKNOWN = 0,
            WHEEL = 1,
            SPHERE_WHEEL = 2,
            SKATE = 3,
            LIP_SYNC = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralAnimationData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<ProceduralControl> controls { get; } = new global::System.Collections.Generic.List<ProceduralControl>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ProceduralControlRotation : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint control_id
        {
            get => __pbn__control_id.GetValueOrDefault();
            set => __pbn__control_id = value;
        }
        public bool ShouldSerializecontrol_id() => __pbn__control_id != null;
        public void Resetcontrol_id() => __pbn__control_id = null;
        private uint? __pbn__control_id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint joint_hash
        {
            get => __pbn__joint_hash.GetValueOrDefault();
            set => __pbn__joint_hash = value;
        }
        public bool ShouldSerializejoint_hash() => __pbn__joint_hash != null;
        public void Resetjoint_hash() => __pbn__joint_hash = null;
        private uint? __pbn__joint_hash;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float duration
        {
            get => __pbn__duration ?? 0f;
            set => __pbn__duration = value;
        }
        public bool ShouldSerializeduration() => __pbn__duration != null;
        public void Resetduration() => __pbn__duration = null;
        private float? __pbn__duration;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong target_id
        {
            get => __pbn__target_id.GetValueOrDefault();
            set => __pbn__target_id = value;
        }
        public bool ShouldSerializetarget_id() => __pbn__target_id != null;
        public void Resettarget_id() => __pbn__target_id = null;
        private ulong? __pbn__target_id;

        [global::ProtoBuf.ProtoMember(5)]
        public uint target_joint_hash
        {
            get => __pbn__target_joint_hash.GetValueOrDefault();
            set => __pbn__target_joint_hash = value;
        }
        public bool ShouldSerializetarget_joint_hash() => __pbn__target_joint_hash != null;
        public void Resettarget_joint_hash() => __pbn__target_joint_hash = null;
        private uint? __pbn__target_joint_hash;

        [global::ProtoBuf.ProtoMember(6)]
        public Quaternion rotation { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue(0f)]
        public float rotation_around_facing
        {
            get => __pbn__rotation_around_facing ?? 0f;
            set => __pbn__rotation_around_facing = value;
        }
        public bool ShouldSerializerotation_around_facing() => __pbn__rotation_around_facing != null;
        public void Resetrotation_around_facing() => __pbn__rotation_around_facing = null;
        private float? __pbn__rotation_around_facing;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum AwarenessChannelName
    {
        AWARENESS_CHANNEL_PROXIMITY = 0,
        AWARENESS_CHANNEL_AUDIO_VOLUME = 1,
        AWARENESS_CHANNEL_GAMEPLAY_0 = 1000,
        AWARENESS_CHANNEL_GAMEPLAY_1 = 1001,
        AWARENESS_CHANNEL_GAMEPLAY_2 = 1002,
        AWARENESS_CHANNEL_GAMEPLAY_3 = 1003,
        AWARENESS_CHANNEL_GAMEPLAY_4 = 1004,
        AWARENESS_CHANNEL_GAMEPLAY_5 = 1005,
        AWARENESS_CHANNEL_GAMEPLAY_6 = 1006,
        AWARENESS_CHANNEL_GAMEPLAY_7 = 1007,
        AWARENESS_CHANNEL_GAMEPLAY_8 = 1008,
        AWARENESS_CHANNEL_GAMEPLAY_9 = 1009,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
