// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Area.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ZoneConnectedLotVersionData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint lotID { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong version { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectedNeighborhoodLot : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint lotId { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong zoneInstanceId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ZoneConnectedData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public global::EA.Sims4.GameInstanceInfoPB instance_info { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint active_lot_id { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public global::System.Collections.Generic.List<ZoneConnectedLotVersionData> lot_versions { get; } = new global::System.Collections.Generic.List<ZoneConnectedLotVersionData>();

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<ConnectedNeighborhoodLot> neighborhood_lots { get; } = new global::System.Collections.Generic.List<ConnectedNeighborhoodLot>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GSI_Open : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string ip { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint port { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string additional_params
        {
            get => __pbn__additional_params ?? "";
            set => __pbn__additional_params = value;
        }
        public bool ShouldSerializeadditional_params() => __pbn__additional_params != null;
        public void Resetadditional_params() => __pbn__additional_params = null;
        private string __pbn__additional_params;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AchievementTrackerUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong account_id
        {
            get => __pbn__account_id.GetValueOrDefault();
            set => __pbn__account_id = value;
        }
        public bool ShouldSerializeaccount_id() => __pbn__account_id != null;
        public void Resetaccount_id() => __pbn__account_id = null;
        private ulong? __pbn__account_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] achievements_completed { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] objectives_completed { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool init_message
        {
            get => __pbn__init_message.GetValueOrDefault();
            set => __pbn__init_message = value;
        }
        public bool ShouldSerializeinit_message() => __pbn__init_message != null;
        public void Resetinit_message() => __pbn__init_message = null;
        private bool? __pbn__init_message;

        [global::ProtoBuf.ProtoMember(5)]
        public bool cheats_used
        {
            get => __pbn__cheats_used.GetValueOrDefault();
            set => __pbn__cheats_used = value;
        }
        public bool ShouldSerializecheats_used() => __pbn__cheats_used != null;
        public void Resetcheats_used() => __pbn__cheats_used = null;
        private bool? __pbn__cheats_used;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AcctGoalsStatusUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong account_id
        {
            get => __pbn__account_id.GetValueOrDefault();
            set => __pbn__account_id = value;
        }
        public bool ShouldSerializeaccount_id() => __pbn__account_id != null;
        public void Resetaccount_id() => __pbn__account_id = null;
        private ulong? __pbn__account_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] goals_updated { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public long[] goal_values { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public long[] goal_objectives { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool[] goals_that_are_money { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public bool[] goals_that_show_progress { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GameTimeCommand : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint clock_speed { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public float game_speed { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong server_time { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong sync_game_time { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public ulong monotonic_time { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool super_speed
        {
            get => __pbn__super_speed ?? false;
            set => __pbn__super_speed = value;
        }
        public bool ShouldSerializesuper_speed() => __pbn__super_speed != null;
        public void Resetsuper_speed() => __pbn__super_speed = null;
        private bool? __pbn__super_speed;

        [global::ProtoBuf.ProtoMember(7)]
        public ulong serial_number
        {
            get => __pbn__serial_number.GetValueOrDefault();
            set => __pbn__serial_number = value;
        }
        public bool ShouldSerializeserial_number() => __pbn__serial_number != null;
        public void Resetserial_number() => __pbn__serial_number = null;
        private ulong? __pbn__serial_number;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SocialNotification : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public SocialNotificationType type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public LocalizedString localized_string { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong account_id
        {
            get => __pbn__account_id.GetValueOrDefault();
            set => __pbn__account_id = value;
        }
        public bool ShouldSerializeaccount_id() => __pbn__account_id != null;
        public void Resetaccount_id() => __pbn__account_id = null;
        private ulong? __pbn__account_id;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong sim_id
        {
            get => __pbn__sim_id.GetValueOrDefault();
            set => __pbn__sim_id = value;
        }
        public bool ShouldSerializesim_id() => __pbn__sim_id != null;
        public void Resetsim_id() => __pbn__sim_id = null;
        private ulong? __pbn__sim_id;

        [global::ProtoBuf.ProtoMember(6)]
        public uint event_uid
        {
            get => __pbn__event_uid.GetValueOrDefault();
            set => __pbn__event_uid = value;
        }
        public bool ShouldSerializeevent_uid() => __pbn__event_uid != null;
        public void Resetevent_uid() => __pbn__event_uid = null;
        private uint? __pbn__event_uid;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SocialNotificationType
    {
        CHAT = 0,
        BUDDYLIST = 1,
        BUDDYLIST_INVITE = 2,
        WALL = 3,
        GAMEPLAY = 4,
        MTX = 5,
        IMMEDIATE = 6,
        GAMEPLAY_ASPIRATION = 7,
        SYSTEM = 8,
        EXCHANGE = 9,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
