// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: BuildBuy.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class LotId : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong household
        {
            get => __pbn__household.GetValueOrDefault();
            set => __pbn__household = value;
        }
        public bool ShouldSerializehousehold() => __pbn__household != null;
        public void Resethousehold() => __pbn__household = null;
        private ulong? __pbn__household;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotOwnershipList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong account_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] lot_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotDescription : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public Vector3 position { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public float rotation { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int tilesize_x { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public int tilesize_z { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public ulong owner_family_id { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public int min_level { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int max_level { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public bool playableLot { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public int lot_price
        {
            get => __pbn__lot_price.GetValueOrDefault();
            set => __pbn__lot_price = value;
        }
        public bool ShouldSerializelot_price() => __pbn__lot_price != null;
        public void Resetlot_price() => __pbn__lot_price = null;
        private int? __pbn__lot_price;

        [global::ProtoBuf.ProtoMember(11)]
        public ulong blueprint_id
        {
            get => __pbn__blueprint_id.GetValueOrDefault();
            set => __pbn__blueprint_id = value;
        }
        public bool ShouldSerializeblueprint_id() => __pbn__blueprint_id != null;
        public void Resetblueprint_id() => __pbn__blueprint_id = null;
        private ulong? __pbn__blueprint_id;

        [global::ProtoBuf.ProtoMember(12)]
        public uint active_plex
        {
            get => __pbn__active_plex.GetValueOrDefault();
            set => __pbn__active_plex = value;
        }
        public bool ShouldSerializeactive_plex() => __pbn__active_plex != null;
        public void Resetactive_plex() => __pbn__active_plex = null;
        private uint? __pbn__active_plex;

        [global::ProtoBuf.ProtoMember(13)]
        public uint building_type
        {
            get => __pbn__building_type.GetValueOrDefault();
            set => __pbn__building_type = value;
        }
        public bool ShouldSerializebuilding_type() => __pbn__building_type != null;
        public void Resetbuilding_type() => __pbn__building_type = null;
        private uint? __pbn__building_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BBOpFailed : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint error_code { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public uint op_id { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BBUndoRedoState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool canUndo { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public bool canRedo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ApplyBlueprintData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public byte[] blueprint_data
        {
            get => __pbn__blueprint_data;
            set => __pbn__blueprint_data = value;
        }
        public bool ShouldSerializeblueprint_data() => __pbn__blueprint_data != null;
        public void Resetblueprint_data() => __pbn__blueprint_data = null;
        private byte[] __pbn__blueprint_data;

        [global::ProtoBuf.ProtoMember(2)]
        public bool furnished
        {
            get => __pbn__furnished.GetValueOrDefault();
            set => __pbn__furnished = value;
        }
        public bool ShouldSerializefurnished() => __pbn__furnished != null;
        public void Resetfurnished() => __pbn__furnished = null;
        private bool? __pbn__furnished;

        [global::ProtoBuf.ProtoMember(3)]
        public bool sell_old_furniture
        {
            get => __pbn__sell_old_furniture.GetValueOrDefault();
            set => __pbn__sell_old_furniture = value;
        }
        public bool ShouldSerializesell_old_furniture() => __pbn__sell_old_furniture != null;
        public void Resetsell_old_furniture() => __pbn__sell_old_furniture = null;
        private bool? __pbn__sell_old_furniture;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong blueprint_id
        {
            get => __pbn__blueprint_id.GetValueOrDefault();
            set => __pbn__blueprint_id = value;
        }
        public bool ShouldSerializeblueprint_id() => __pbn__blueprint_id != null;
        public void Resetblueprint_id() => __pbn__blueprint_id = null;
        private ulong? __pbn__blueprint_id;

        [global::ProtoBuf.ProtoMember(6)]
        public long delta_funds
        {
            get => __pbn__delta_funds.GetValueOrDefault();
            set => __pbn__delta_funds = value;
        }
        public bool ShouldSerializedelta_funds() => __pbn__delta_funds != null;
        public void Resetdelta_funds() => __pbn__delta_funds = null;
        private long? __pbn__delta_funds;

        [global::ProtoBuf.ProtoMember(7)]
        public int size_x
        {
            get => __pbn__size_x.GetValueOrDefault();
            set => __pbn__size_x = value;
        }
        public bool ShouldSerializesize_x() => __pbn__size_x != null;
        public void Resetsize_x() => __pbn__size_x = null;
        private int? __pbn__size_x;

        [global::ProtoBuf.ProtoMember(8)]
        public int size_z
        {
            get => __pbn__size_z.GetValueOrDefault();
            set => __pbn__size_z = value;
        }
        public bool ShouldSerializesize_z() => __pbn__size_z != null;
        public void Resetsize_z() => __pbn__size_z = null;
        private int? __pbn__size_z;

        [global::ProtoBuf.ProtoMember(9)]
        public int bedroom_count
        {
            get => __pbn__bedroom_count.GetValueOrDefault();
            set => __pbn__bedroom_count = value;
        }
        public bool ShouldSerializebedroom_count() => __pbn__bedroom_count != null;
        public void Resetbedroom_count() => __pbn__bedroom_count = null;
        private int? __pbn__bedroom_count;

        [global::ProtoBuf.ProtoMember(10)]
        public int bathroom_count
        {
            get => __pbn__bathroom_count.GetValueOrDefault();
            set => __pbn__bathroom_count = value;
        }
        public bool ShouldSerializebathroom_count() => __pbn__bathroom_count != null;
        public void Resetbathroom_count() => __pbn__bathroom_count = null;
        private int? __pbn__bathroom_count;

        [global::ProtoBuf.ProtoMember(11)]
        [global::System.ComponentModel.DefaultValue(0)]
        public int front_side
        {
            get => __pbn__front_side ?? 0;
            set => __pbn__front_side = value;
        }
        public bool ShouldSerializefront_side() => __pbn__front_side != null;
        public void Resetfront_side() => __pbn__front_side = null;
        private int? __pbn__front_side;

        [global::ProtoBuf.ProtoMember(12)]
        public ulong region_id
        {
            get => __pbn__region_id.GetValueOrDefault();
            set => __pbn__region_id = value;
        }
        public bool ShouldSerializeregion_id() => __pbn__region_id != null;
        public void Resetregion_id() => __pbn__region_id = null;
        private ulong? __pbn__region_id;

        [global::ProtoBuf.ProtoMember(13)]
        public bool allow_custom_textures
        {
            get => __pbn__allow_custom_textures.GetValueOrDefault();
            set => __pbn__allow_custom_textures = value;
        }
        public bool ShouldSerializeallow_custom_textures() => __pbn__allow_custom_textures != null;
        public void Resetallow_custom_textures() => __pbn__allow_custom_textures = null;
        private bool? __pbn__allow_custom_textures;

        [global::ProtoBuf.ProtoMember(14)]
        public byte[] creator_uuid
        {
            get => __pbn__creator_uuid;
            set => __pbn__creator_uuid = value;
        }
        public bool ShouldSerializecreator_uuid() => __pbn__creator_uuid != null;
        public void Resetcreator_uuid() => __pbn__creator_uuid = null;
        private byte[] __pbn__creator_uuid;

        [global::ProtoBuf.ProtoMember(15)]
        public ulong creator_id
        {
            get => __pbn__creator_id.GetValueOrDefault();
            set => __pbn__creator_id = value;
        }
        public bool ShouldSerializecreator_id() => __pbn__creator_id != null;
        public void Resetcreator_id() => __pbn__creator_id = null;
        private ulong? __pbn__creator_id;

        [global::ProtoBuf.ProtoMember(16)]
        [global::System.ComponentModel.DefaultValue("")]
        public string creator_name
        {
            get => __pbn__creator_name ?? "";
            set => __pbn__creator_name = value;
        }
        public bool ShouldSerializecreator_name() => __pbn__creator_name != null;
        public void Resetcreator_name() => __pbn__creator_name = null;
        private string __pbn__creator_name;

        [global::ProtoBuf.ProtoMember(17)]
        public ulong modifier_id
        {
            get => __pbn__modifier_id.GetValueOrDefault();
            set => __pbn__modifier_id = value;
        }
        public bool ShouldSerializemodifier_id() => __pbn__modifier_id != null;
        public void Resetmodifier_id() => __pbn__modifier_id = null;
        private ulong? __pbn__modifier_id;

        [global::ProtoBuf.ProtoMember(18)]
        [global::System.ComponentModel.DefaultValue("")]
        public string modifier_name
        {
            get => __pbn__modifier_name ?? "";
            set => __pbn__modifier_name = value;
        }
        public bool ShouldSerializemodifier_name() => __pbn__modifier_name != null;
        public void Resetmodifier_name() => __pbn__modifier_name = null;
        private string __pbn__modifier_name;

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue("")]
        public string zone_name
        {
            get => __pbn__zone_name ?? "";
            set => __pbn__zone_name = value;
        }
        public bool ShouldSerializezone_name() => __pbn__zone_name != null;
        public void Resetzone_name() => __pbn__zone_name = null;
        private string __pbn__zone_name;

        [global::ProtoBuf.ProtoMember(20)]
        public ulong[] lot_traits { get; set; }

        [global::ProtoBuf.ProtoMember(21)]
        public UniversityHousingConfiguration university_housing_configuration { get; set; }

        [global::ProtoBuf.ProtoMember(22)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool keep_venue_type
        {
            get => __pbn__keep_venue_type ?? false;
            set => __pbn__keep_venue_type = value;
        }
        public bool ShouldSerializekeep_venue_type() => __pbn__keep_venue_type != null;
        public void Resetkeep_venue_type() => __pbn__keep_venue_type = null;
        private bool? __pbn__keep_venue_type;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlexRatingMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint plex_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int size_rating { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int amenity_rating { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int environment_rating { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint real_bed_count { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public uint real_toilet_count { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PlexRatingUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<PlexRatingMessage> ratings { get; } = new global::System.Collections.Generic.List<PlexRatingMessage>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotValueMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint plex_id { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public int unfurnished_value { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int furnished_value { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int architecture_value { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LotValueUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong zone_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<LotValueMessage> lot_values { get; } = new global::System.Collections.Generic.List<LotValueMessage>();

        [global::ProtoBuf.ProtoMember(3)]
        public PlexRatingUpdate plex_rating_update { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool update_cache
        {
            get => __pbn__update_cache ?? false;
            set => __pbn__update_cache = value;
        }
        public bool ShouldSerializeupdate_cache() => __pbn__update_cache != null;
        public void Resetupdate_cache() => __pbn__update_cache = null;
        private bool? __pbn__update_cache;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SetRentPriceData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong zone_id
        {
            get => __pbn__zone_id.GetValueOrDefault();
            set => __pbn__zone_id = value;
        }
        public bool ShouldSerializezone_id() => __pbn__zone_id != null;
        public void Resetzone_id() => __pbn__zone_id = null;
        private ulong? __pbn__zone_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong house_description_id
        {
            get => __pbn__house_description_id.GetValueOrDefault();
            set => __pbn__house_description_id = value;
        }
        public bool ShouldSerializehouse_description_id() => __pbn__house_description_id != null;
        public void Resethouse_description_id() => __pbn__house_description_id = null;
        private ulong? __pbn__house_description_id;

        [global::ProtoBuf.ProtoMember(3)]
        public uint rent_price
        {
            get => __pbn__rent_price.GetValueOrDefault();
            set => __pbn__rent_price = value;
        }
        public bool ShouldSerializerent_price() => __pbn__rent_price != null;
        public void Resetrent_price() => __pbn__rent_price = null;
        private uint? __pbn__rent_price;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class InitialRentPriceUpdate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SetRentPriceData> rent_prices { get; } = new global::System.Collections.Generic.List<SetRentPriceData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
