// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Restaurant.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RecipeItem : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong recipe_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(ItemType.NORMAL)]
        public ItemType item_type
        {
            get => __pbn__item_type ?? ItemType.NORMAL;
            set => __pbn__item_type = value;
        }
        public bool ShouldSerializeitem_type() => __pbn__item_type != null;
        public void Resetitem_type() => __pbn__item_type = null;
        private ItemType? __pbn__item_type;

        [global::ProtoBuf.ProtoMember(3)]
        public int price_override
        {
            get => __pbn__price_override.GetValueOrDefault();
            set => __pbn__price_override = value;
        }
        public bool ShouldSerializeprice_override() => __pbn__price_override != null;
        public void Resetprice_override() => __pbn__price_override = null;
        private int? __pbn__price_override;

        [global::ProtoBuf.ProtoContract()]
        public enum ItemType
        {
            NORMAL = 0,
            SPECIAL = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Course : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<RecipeItem> items { get; } = new global::System.Collections.Generic.List<RecipeItem>();

        [global::ProtoBuf.ProtoMember(2)]
        public uint course_tag
        {
            get => __pbn__course_tag.GetValueOrDefault();
            set => __pbn__course_tag = value;
        }
        public bool ShouldSerializecourse_tag() => __pbn__course_tag != null;
        public void Resetcourse_tag() => __pbn__course_tag = null;
        private uint? __pbn__course_tag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Menu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<Course> courses { get; } = new global::System.Collections.Generic.List<Course>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimOrders : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SimOrder> sim_orders { get; } = new global::System.Collections.Generic.List<SimOrder>();

        [global::ProtoBuf.ProtoMember(2)]
        public uint meal_cost
        {
            get => __pbn__meal_cost.GetValueOrDefault();
            set => __pbn__meal_cost = value;
        }
        public bool ShouldSerializemeal_cost() => __pbn__meal_cost != null;
        public void Resetmeal_cost() => __pbn__meal_cost = null;
        private uint? __pbn__meal_cost;

        [global::ProtoBuf.ProtoMember(3)]
        public bool is_recommendation
        {
            get => __pbn__is_recommendation.GetValueOrDefault();
            set => __pbn__is_recommendation = value;
        }
        public bool ShouldSerializeis_recommendation() => __pbn__is_recommendation != null;
        public void Resetis_recommendation() => __pbn__is_recommendation = null;
        private bool? __pbn__is_recommendation;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SimOrder : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong sim_id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong recipe_id
        {
            get => __pbn__recipe_id.GetValueOrDefault();
            set => __pbn__recipe_id = value;
        }
        public bool ShouldSerializerecipe_id() => __pbn__recipe_id != null;
        public void Resetrecipe_id() => __pbn__recipe_id = null;
        private ulong? __pbn__recipe_id;

        [global::ProtoBuf.ProtoMember(3)]
        public bool locked
        {
            get => __pbn__locked.GetValueOrDefault();
            set => __pbn__locked = value;
        }
        public bool ShouldSerializelocked() => __pbn__locked != null;
        public void Resetlocked() => __pbn__locked = null;
        private bool? __pbn__locked;

        [global::ProtoBuf.ProtoMember(4)]
        public uint course_tag
        {
            get => __pbn__course_tag.GetValueOrDefault();
            set => __pbn__course_tag = value;
        }
        public bool ShouldSerializecourse_tag() => __pbn__course_tag != null;
        public void Resetcourse_tag() => __pbn__course_tag = null;
        private uint? __pbn__course_tag;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ShowMenu : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Menu menu { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public global::System.Collections.Generic.List<SimOrder> sim_orders { get; } = new global::System.Collections.Generic.List<SimOrder>();

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] sim_ids { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public bool chef_order
        {
            get => __pbn__chef_order.GetValueOrDefault();
            set => __pbn__chef_order = value;
        }
        public bool ShouldSerializechef_order() => __pbn__chef_order != null;
        public void Resetchef_order() => __pbn__chef_order = null;
        private bool? __pbn__chef_order;

        [global::ProtoBuf.ProtoMember(5)]
        public uint running_bill_total
        {
            get => __pbn__running_bill_total.GetValueOrDefault();
            set => __pbn__running_bill_total = value;
        }
        public bool ShouldSerializerunning_bill_total() => __pbn__running_bill_total != null;
        public void Resetrunning_bill_total() => __pbn__running_bill_total = null;
        private uint? __pbn__running_bill_total;

        [global::ProtoBuf.ProtoMember(6)]
        public bool recommend_order
        {
            get => __pbn__recommend_order.GetValueOrDefault();
            set => __pbn__recommend_order = value;
        }
        public bool ShouldSerializerecommend_order() => __pbn__recommend_order != null;
        public void Resetrecommend_order() => __pbn__recommend_order = null;
        private bool? __pbn__recommend_order;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Order : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<SimOrder> sim_orders { get; } = new global::System.Collections.Generic.List<SimOrder>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RestaurantConfiguration : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint attire_id
        {
            get => __pbn__attire_id.GetValueOrDefault();
            set => __pbn__attire_id = value;
        }
        public bool ShouldSerializeattire_id() => __pbn__attire_id != null;
        public void Resetattire_id() => __pbn__attire_id = null;
        private uint? __pbn__attire_id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong preset_id
        {
            get => __pbn__preset_id.GetValueOrDefault();
            set => __pbn__preset_id = value;
        }
        public bool ShouldSerializepreset_id() => __pbn__preset_id != null;
        public void Resetpreset_id() => __pbn__preset_id = null;
        private ulong? __pbn__preset_id;

        [global::ProtoBuf.ProtoMember(3)]
        public Menu custom_menu { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public global::System.Collections.Generic.List<CareerOutfit> outfits { get; } = new global::System.Collections.Generic.List<CareerOutfit>();

        [global::ProtoBuf.ProtoContract()]
        public enum RestaurantOutfitType
        {
            MALE_CHEF = 0,
            FEMALE_CHEF = 1,
            MALE_WAITER = 2,
            FEMALE_WAITER = 3,
            MALE_HOST = 4,
            FEMALE_HOST = 5,
        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
