// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: Vehicles.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace EA.Sims4.Network
{

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleControl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint control_id
        {
            get => __pbn__control_id.GetValueOrDefault();
            set => __pbn__control_id = value;
        }
        public bool ShouldSerializecontrol_id() => __pbn__control_id != null;
        public void Resetcontrol_id() => __pbn__control_id = null;
        private uint? __pbn__control_id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(VehicleControlType.UNKNOWN)]
        public VehicleControlType control_type
        {
            get => __pbn__control_type ?? VehicleControlType.UNKNOWN;
            set => __pbn__control_type = value;
        }
        public bool ShouldSerializecontrol_type() => __pbn__control_type != null;
        public void Resetcontrol_type() => __pbn__control_type = null;
        private VehicleControlType? __pbn__control_type;

        [global::ProtoBuf.ProtoMember(3)]
        public uint joint_name_hash
        {
            get => __pbn__joint_name_hash.GetValueOrDefault();
            set => __pbn__joint_name_hash = value;
        }
        public bool ShouldSerializejoint_name_hash() => __pbn__joint_name_hash != null;
        public void Resetjoint_name_hash() => __pbn__joint_name_hash = null;
        private uint? __pbn__joint_name_hash;

        [global::ProtoBuf.ProtoMember(4)]
        public uint reference_joint_name_hash
        {
            get => __pbn__reference_joint_name_hash.GetValueOrDefault();
            set => __pbn__reference_joint_name_hash = value;
        }
        public bool ShouldSerializereference_joint_name_hash() => __pbn__reference_joint_name_hash != null;
        public void Resetreference_joint_name_hash() => __pbn__reference_joint_name_hash = null;
        private uint? __pbn__reference_joint_name_hash;

        [global::ProtoBuf.ProtoMember(5)]
        public bool enable_terrain_alignment
        {
            get => __pbn__enable_terrain_alignment.GetValueOrDefault();
            set => __pbn__enable_terrain_alignment = value;
        }
        public bool ShouldSerializeenable_terrain_alignment() => __pbn__enable_terrain_alignment != null;
        public void Resetenable_terrain_alignment() => __pbn__enable_terrain_alignment = null;
        private bool? __pbn__enable_terrain_alignment;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string bump_sound_name
        {
            get => __pbn__bump_sound_name ?? "";
            set => __pbn__bump_sound_name = value;
        }
        public bool ShouldSerializebump_sound_name() => __pbn__bump_sound_name != null;
        public void Resetbump_sound_name() => __pbn__bump_sound_name = null;
        private string __pbn__bump_sound_name;

        [global::ProtoBuf.ProtoContract()]
        public enum VehicleControlType
        {
            UNKNOWN = 0,
            WHEEL = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VehicleData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<VehicleControl> controls { get; } = new global::System.Collections.Generic.List<VehicleControl>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
